### ISSUE TITLE
Debug console does not allow evaluation on the fly in 'Test debug' mode

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode-java-test#106] opened 2018-02-02 13:36 UTC
Reproduce: 
1. Create test where you set some variable and put a breakpoint on the line after you set it.
2. Press 'Debug test' on the test method code lens. 
3. Go to Debug Console and type your variable name.
Debug Console prints: `Please specify projectName in launch.json.`

Seems like runtime generated launch.json `projectName` attribute is missing.

**Comment by ansyral** [comment] 2018-02-09 06:15
@michelkaporin  thanks for reporting this, it is duplicate of https://github.com/Microsoft/vscode-java-test/issues/102

**Closed** 2018-02-09 06:15 UTC
