### ISSUE TITLE
Adding new java package under test/src doesn't reveal tests in Test Explorer

### ISSUE THREAD

**Issue by stanlick** [microsoft/vscode-java-test#758] opened 2019-07-24 17:09 UTC
I started with a Spring Boot starter and the included tests worked fine.  I added a new package and the tests never showed up under the test explorer.  Strange, the folder name of the new source folder (package) was a different color as well.  If I add new tests to the original folder, it all works great

**Comment by jdneo** [comment] 2019-07-25 01:58
Hi @stanlick,

I tried on my side but not able to repro the problem. Some questions might need your help to clarify.
- Are you creating new package under `test/src`, or do you mean `src/test/java`.
- Is it possible for you to share your sample project to let us help investigate the problem?

Thanks.

**Comment by stanlick** [comment] 2019-07-25 13:44
Project is [here](https://github.com/stanlick/JavaGently). It started off as a Spring project where I added a new folder (path segment) under test/java/com/example/demo named **weird**.  I then added a **MiscTests**.java there that does not appear under Test Explorer.

Peace,
Scott

**Comment by jdneo** [comment] 2019-07-26 07:40
Thank you @stanlick

I can repro it now. Let me investigate the root cause. For now, a workaround would be reload the VS Code to make it appear in the explorer. Sorry for the inconvenience.

**Comment by jdneo** [comment] 2019-10-12 08:54
Related with https://github.com/eclipse/eclipse.jdt.ls/issues/1137

**Comment by jdneo** [comment] 2019-10-15 01:39
Hi @stanlick,

The PR for fixing the upstream issue has been merged. I believe this problem will be addressed once the new version of Java Support extension get published.

So I'm closing this issue for now. If you find this problem still occurs after that, please feel free to let me know.

Thanks.

**Closed by jdneo** 2019-10-15 01:39 UTC
Labels: bug, upstream
