### ISSUE TITLE
Cannot see full stacktrace in TestNG tests

### ISSUE THREAD

**Issue by itaygoz** [microsoft/vscode-java-test#1291] opened 2021-08-22 08:04 UTC
Hi, this is my env
![image](https://user-images.githubusercontent.com/48314049/130346891-8316ebb2-0ab4-4c67-826b-28315ca0c2aa.png)
and I'm using Test Runner for Java v0.31.2

I'm working on a Spring project and while I'm having Failed to load ApplicationContext Error I can't see the reason.
![image](https://user-images.githubusercontent.com/48314049/130347003-6450e46c-5fa3-40cc-977c-93a715e9c70f.png)
 It seems like the stack trace is partial.

Also, I can't see the stack trace in the Debug Console because I'm getting a lot of logs while an error occurs and the log has a limited number of lines, so I can't see the relevant error because it was removed.

In the last version I could see the full stack trace in the report, and to tell the truth, it was easier to look at the report because it was on a separate page.

**Comment by jdneo** [comment] 2021-08-23 01:52
@itaygoz Could you please provide a sample project which can repro this issue?

**Comment by itaygoz** [comment] 2021-08-23 07:19
Hi yes, https://github.com/itaygoz/Example
![image](https://user-images.githubusercontent.com/48314049/130406456-447224e4-94ae-4f68-a323-19039e08d16d.png)
Can't see what bean was failed.

Thanks!

**Comment by jdneo** [comment] 2021-08-23 08:18
Looks wired. I debugged into the code, originally it's 

`... at%20org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java%3A455)%5C%5Cr%5C%5Cn%5C%5Ctat%20org.testng.internal.Invoker.invokeConfigurations(Invoker.java%3A222)%5C%5Cr%5C%5Cn%5C%5Ct ...`

And passing it to `decodeURIComponent()` gives correct result. But I don't know why VS Code rendered it in that way.

**Comment by jdneo** [comment] 2021-08-23 10:22
I guess I found the root cause: It's because a wrong string is passed to generate the stack trace link, which corrupts the markdown string. A fix is provided in #1295.

**Comment by itaygoz** [comment] 2021-08-23 10:24
Great, thanks for the fast reply

**Comment by jdneo** [comment] 2021-08-28 03:38
Fixed in #1286

**Closed by jdneo** 2021-08-28 03:38 UTC
Labels: bug

**Comment by jdneo** [comment] 2021-09-13 01:50
In case anyone is blocked by this issue, you can install this build before the next version is released: 
[vscode-java-test-0.31.3.vsix.zip](https://github.com/microsoft/vscode-java-test/files/7150843/vscode-java-test-0.31.3.vsix.zip)

**Comment by jdneo** [comment] 2021-09-22 08:39
To verify this issue:

1. Open a TestNG project, i.e. http://www.mkyong.com/wp-content/uploads/2014/01/TestNG-Spring-Example.zip
2. Run a failed test, i.e. com.mkyong.testng.examples.dependency.App.method1()
3. Check if the stacktrace is not truncated

**Comment by Eskibear** [comment] 2021-09-23 06:10
verified
