### ISSUE TITLE
NoClassDefFoundError: org/junit/runner/JUnitCore

### ISSUE THREAD

**Issue by dsyer** [Microsoft/vscode-java-test#34] opened 2017-12-01 19:24 UTC
I can run tests in a single module project, but as soon as I have multiple modules (e.g. opening up https://github.com/spring-cloud/spring-cloud-function/tree/master/spring-cloud-function-samples since that was what I was working on), I get this:

```
Error occured: Exception in thread "main" Error occured: java.lang.NoClassDefFoundError: org/junit/runner/JUnitCore
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
Error occured: 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.microsoft.java.test.runner.JUnitLauncher.main(JUnitLauncher.java:20)
Caused by: java.lang.ClassNotFoundException: org.junit.runner.JUnitCore
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more
```

**Comment by pandabrand** [comment] 2017-12-01 22:21
I'm having this issue as well, I have creating a fresh project using Maven, and trying to use this extension I get the above error.

**Comment by ansyral** [comment] 2017-12-04 03:47
@dsyer @pandabrand  thanks a lot for the feedback! I can repro it and it is class path resolution issue. I'm Working on it.

**Comment by ansyral** [comment] 2017-12-04 15:02
accidently closed it when merging pr..

**Comment by ansyral** [comment] 2018-01-05 07:45
The issue has been fixed in 0.2.0 release. So I'm gonna close it right now. You are free to reopen it if it still doesn't work.

**Comment by DeadRabbits307** [comment] 2018-01-27 19:15
Using 0.2.0 I still get the same errors...

**Comment by Stiixxy** [comment] 2018-02-09 16:42
Using 0.2.0 as well also getting the same error
`Error occured: Exception in thread "main" Error occured: java.lang.NoClassDefFoundError: org/junit/runner/JUnitCore
Error occured: 	at java.lang.ClassLoader.defineClass1(Native Method)
Error occured: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)Error occured: 
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
Error occured: 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.microsoft.java.test.runner.JUnitLauncher.main(JUnitLauncher.java:20)
Error occured: Caused by: java.lang.ClassNotFoundException: org.junit.runner.JUnitCore
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Error occured: 	... 13 more
`

Maybe also good to mention that i use gradle, and when i run gradle test i get BUILD_SUCCESFUL
here is my build.gradle
`buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath ("org.junit.platform:junit-platform-gradle-plugin:1.0.1")
    }
}

apply plugin: 'java'
apply plugin: 'org.junit.platform.gradle.plugin'

repositories{
    jcenter()
}

dependencies{
    testCompile("org.junit.jupiter:junit-jupiter-api:5.0.1")
    
    testRuntime(
        "org.junit.jupiter:junit-jupiter-engine:5.0.1",
        'org.junit.vintage:junit-vintage-engine:4.12.1',
        'org.junit.platform:junit-platform-launcher:1.0.1',
        'org.junit.platform:junit-platform-runner:1.0.1'
    )
}

sourceSets {
    main.java.srcDir "src"
    test.java.srcDir "test"
}
`

**Comment by coderfin** [comment] 2018-02-12 19:51
I was able to resolve this problem in v0.3.0 by installing the [Java IDE Pack extension](https://github.com/paulvi/vscode-java-ide-pack).  I can now `Run Test` and `Debug Test` directly in VSCode and view the Test Report.

**Comment by nrc4867** [comment] 2018-02-19 05:28
I'm also having this issue on v0.3.0 and could not replicate @coderfin resoultion

'Error occurred: Exception in thread "main" Error occurred: java.lang.NoClassDefFoundError: org/junit/runner/JUnitCoreError occurred: 
Error occurred: 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1007)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:801)
Error occurred: 	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:699)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:622)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at com.microsoft.java.test.runner.JUnitLauncher.main(JUnitLauncher.java:20)
Caused by: java.lang.ClassNotFoundException: org.junit.runner.JUnitCoreError occurred: 
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 10 more
'

**Comment by ansyral** [comment] 2018-02-26 07:24
seems some class path isn't successfully resolved, could someone help share a piece of code to repro the error?

**Comment by ansyral** [comment] 2018-02-26 09:08
BTW, which version of Junit are you using?

**Comment by vasilescur** [comment] 2018-02-26 21:34
I'm running into the same issue. I downloaded the junit-4.12.jar and hamcrest-core-1.3.jar and placed them in my project's folder as per the JUnit installation guide, but the classpath generated by this extension that gets used in the command to run the tests seems not to be able to see jar files in the folder. I suggest apending `./*` to the generated classpath.

**Comment by ansyral** [comment] 2018-02-27 02:38
@vasilescur which kind of project management are you using? maven, gradle or eclipse projects, .etc? could you check whether your project'classpath contains junit-4.12.jar?

**Comment by vasilescur** [comment] 2018-02-27 03:31
@ansyral That solved my issue. I wasn't using any of those, just placing classes in a folder. I've (learned and) switched to using Gradle, and everything works fine now.

**Comment by ansyral** [comment] 2018-02-27 07:41
@Stiixxy are you using Junit5? We haven't supported it yet, we'll work on it soon.

**Comment by stejsoftware** [comment] 2018-03-07 15:21
I had the same issue. 
My test were in the default package. It appear to have cleaned its self up when I put the test in a package and then restarted VSCode.

**Comment by ansyral** [comment] 2018-03-09 06:58
@stejsoftware  sorry I couldn't repro using your code.  Could you check whether your pom.xml configure junit correctly?

**Comment by cagdasgerede** [comment] 2018-04-06 22:34
Make sure you open the root folder of the project. If you open an individual file or a sub folder in VS code then you will see this error.

**Comment by jdneo** [comment] 2018-12-28 08:37
@jgheewala Did you still see this errors in the latest Test Runner extension?

**Comment by jdneo** [comment] 2019-03-08 05:55
Closing this issue since it's inactive for a long time.

**Closed by jdneo** 2019-03-08 05:55 UTC
Labels: need more info
