### ISSUE TITLE
No code lens in version 0.23.0

### ISSUE THREAD

**Issue by ecmel** [microsoft/vscode-java-test#1014] opened 2020-06-08 19:08 UTC
Code lens is not working in 0.23.0 version.

**Comment by jdneo** [comment] 2020-06-09 00:52
@ecmel We did a change in 0.23.0, which will not resolve Code Lens in non-test source path.

Could you check if you are editing source files under test source path? Or could you please share a sample project to us?

**Comment by ecmel** [comment] 2020-06-09 04:41
@jdneo I created the project using maven-archetype-quickstart. JUnit 4 test is under src/test/java/{package}

**Comment by jdneo** [comment] 2020-06-09 04:59
I cannot repro on my side:

![image](https://user-images.githubusercontent.com/6193897/84107489-5649bc80-aa50-11ea-8d25-7416f28d2494.png)

Please check:
1. Is the language server running in `LightWeight` mode? -- Check the setting `java.server.launchMode`
2. Is the language server working: You can test this by simply run the `main` method in src/main/java/{package}/App.java

**Comment by ecmel** [comment] 2020-06-09 05:21
1. Language server is running in default hybrid mode.
2. Main method can be executed.
![Capture1](https://user-images.githubusercontent.com/1858678/84108915-1079fd80-aa2a-11ea-930b-1b3aa3878246.PNG)

Code lens disappeared after 0.23.0 upgrade:
![Capture2](https://user-images.githubusercontent.com/1858678/84108969-36070700-aa2a-11ea-97ab-e21a98120528.PNG)

**Comment by jdneo** [comment] 2020-06-09 06:40
I see. I think the major difference between our usage is: I'm opening the folder locally but you are in WSL.

I also noticed that in your file explorer, there is no `.classpath` & `.project` files. Did you hide them from the explorer?

**Comment by ecmel** [comment] 2020-06-09 06:42
Yes .classpath and .project are hidden and I am on wsl

**Comment by jdneo** [comment] 2020-06-09 06:53
@ecmel would you mind to share the content of the `.classpath` file?

**Comment by ecmel** [comment] 2020-06-09 06:54
`
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" output="target/classes" path="src/main/java">
		<attributes>
			<attribute name="optional" value="true"/>
			<attribute name="maven.pomderived" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="target/test-classes" path="src/test/java">
		<attributes>
			<attribute name="optional" value="true"/>
			<attribute name="maven.pomderived" value="true"/>
			<attribute name="test" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.7">
		<attributes>
			<attribute name="maven.pomderived" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="con" path="org.eclipse.m2e.MAVEN2_CLASSPATH_CONTAINER">
		<attributes>
			<attribute name="maven.pomderived" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" path="target/generated-sources/annotations">
		<attributes>
			<attribute name="optional" value="true"/>
			<attribute name="maven.pomderived" value="true"/>
			<attribute name="ignore_optional_problems" value="true"/>
			<attribute name="m2e-apt" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="target/test-classes" path="target/generated-test-sources/test-annotations">
		<attributes>
			<attribute name="optional" value="true"/>
			<attribute name="maven.pomderived" value="true"/>
			<attribute name="ignore_optional_problems" value="true"/>
			<attribute name="m2e-apt" value="true"/>
			<attribute name="test" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="output" path="target/classes"/>
</classpath>
`

**Comment by jdneo** [comment] 2020-06-09 08:08
@ecmel this `.classpath` looks good.

I need more time to figure out the root cause. Thank you for reporting.

**Comment by rqueraud** [comment] 2020-06-09 08:14
I am also using WSL and I can confirm that it no longer work with 0.23.0.
It was working yesterday, so I suppose that it is due to the update.

**Comment by jdneo** [comment] 2020-06-09 08:27
@all For all who encounters this problem, please revert to 0.22.4 as a workaround. I'll update my findings later.

**Comment by Rawi666** [comment] 2020-06-10 07:27
I'd also like to add that the lenses stopped working when working remotely using Remote SSH plugin, so it's not only when using WSL.

**Comment by jdneo** [comment] 2020-06-12 05:10
Not sure if this is a bug of VS Code or not. I created an [issue](https://github.com/microsoft/vscode/issues/99938) at VS Code repo. Let wait for the answer.

**Comment by jimboowens** [comment] 2020-06-12 18:08
I created an issue at the VSCode level, #99987, which was promptly closed by member @sandy081. At their behest, I then refiled under the vscode-java-test repo at issue #1015, which has not yet been tagged, labeled, or assigned. Which is to say I am having the same issue. And filing it at the VSCode Repo might not get you anywhere.

**Comment by jdneo** [comment] 2020-06-28 01:31
@all

The upstream issue has been fixed. So the bug should disappear after the new VS Code stable version released. For now, if you do want to have the Code Lens in Remote scenario, there are two workarounds:

- Downgrade to **0.22.4**
- Use the latest VS Code **Insider**

**Comment by jdneo** [comment] 2020-07-13 03:15
Just tested and the issue should have been fixed in VS Code 1.47.0. Close it.

**Closed by jdneo** 2020-07-13 03:15 UTC
Labels: bug, upstream
