### ISSUE TITLE
Couldn't find Java home

### ISSUE THREAD

**Issue by kevinjuan25** [Microsoft/vscode-java-test#318] opened 2018-09-26 06:44 UTC
When I go to open my test file, I get a notification that Java Test Runner couldn't find Java home, and all of my tests are skipped. I have my `JAVA_HOME` set correctly since Java Language Support works. I'm working on mac OS using jdk 1.8.0_181 and VS Code version 1.27.2 with the latest version of Java Test Runner. I'm rather new to VS Code and Java, so any advice would help. I can also provide more information if needed.

**Comment by jdneo** [comment] 2018-09-26 06:51
@kevinjuan25 May I ask what kind of project are you developing? Would you mind to share a link to us if it is an open source project?

**Comment by kevinjuan25** [comment] 2018-09-26 07:06
@jdneo All of my projects are eclipse projects for school, so they’re not publicly available. What would you need to see from them?

**Comment by jdneo** [comment] 2018-09-26 07:17
Hmm, I ask for this is because of that according to the current implementation,  `Couldn't find Java home` might not be caused by failing to find the Java Home. So it would be great if I can repro this issue and investigate what's happening.

**Comment by kevinjuan25** [comment] 2018-09-26 07:53
If it helps, here is a screenshot of problems VS Code is giving me.
![screen shot 2018-09-26 at 3 52 03 am](https://user-images.githubusercontent.com/31362150/46065288-ac24e680-c13f-11e8-9522-e39d1f9640e1.png)

**Comment by jdneo** [comment] 2018-09-26 08:02
Yeah, I think the screenshot explains the root cause. Since there is something wrong with the classpath, then the test runner extension will throw an error when executing this line of code: https://github.com/Microsoft/vscode-java-test/blob/master/extension/src/extension.ts#L130

So actually this is not caused by java home but classpath issue.

**Comment by kevinjuan25** [comment] 2018-09-26 08:10
How would I go about fixing that? I'm not very familiar with classpath since most of my Unit tests were done in Eclipse with no issues like this.

**Comment by jdneo** [comment] 2018-09-26 08:48
You might ask for help in the gitter channel: https://gitter.im/redhat-developer/vscode-java?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by jdneo** [comment] 2018-09-27 01:50
@kevinjuan25  Closing it for now but feel free to reopen it if you have any question. 😄

**Closed by jdneo** 2018-09-27 01:50 UTC

**Comment by kevinjuan25** [comment] 2018-09-28 17:43
This was the console info I got for one of my JUnit test files created in Eclipse. I haven't had any success trying to decipher where to root out the issue. 
![screen shot 2018-09-28 at 1 41 12 pm](https://user-images.githubusercontent.com/31362150/46224490-8278e480-c324-11e8-8ca0-6959f01aada8.png)

**Comment by jdneo** [comment] 2018-09-29 01:41
As you can see the project has lots of compile errors. It would be better to solve them first.

It would be easier for us to investigate and help you if you can provide the sample project which can repro these errors

**Comment by kevinjuan25** [comment] 2018-09-29 16:39
They all compile fine on Eclipse, so I don't think there is an issue with the projects themselves, but rather the inability for the Java extensions to properly find the JUnit package or Java home as the error message pointed out. Unfortunately, I don't think this is replicable on all machines, and seems to be an issue specifically with how it's set up on my machine.

**Comment by jdneo** [comment] 2018-09-30 02:09
Hmm, what kind of the project is? Is it a Maven / Gradle or an Eclipse project?

**Comment by kevinjuan25** [comment] 2018-09-30 02:18
Eclipse

**Comment by jdneo** [comment] 2018-09-30 03:09
Ok, so if the project cannot be shared. Would you mind to share the file structure? This could help us understand the kind of the project.

**Comment by kevinjuan25** [comment] 2018-09-30 16:04
Here's the project file hierarchy in the workspace
![screen shot 2018-09-30 at 12 03 21 pm](https://user-images.githubusercontent.com/31362150/46259556-ea583800-c4a8-11e8-9736-54971824113a.png)

**Comment by kevinjuan25** [comment] 2018-10-03 16:46
<img width="677" alt="screen shot 2018-10-03 at 12 45 54 pm" src="https://user-images.githubusercontent.com/31362150/46425692-5685a680-c70a-11e8-99a6-7b3f412f5d35.png">
Don't know if this will help, but here is my `launch.test.json`
