### ISSUE TITLE
Markdown formatting issue with dollar sign (probably)

### ISSUE THREAD

**Issue by matter-it-does** [microsoft/vscode-java-test#1424] opened 2022-05-26 10:49 UTC
The markdown formatting in  the external tab is broken with a certain kind of message. Attached is the small repro project.

Code is as follows

```java
package com.blah.servimpl;
import org.junit.jupiter.api.Test;
public class AppTest{
    
    @Test
    public void test(){
        throw new IllegalArgumentException("com.mongodb.MongoCommandException: Command failed with error 2 (BadValue): 'Plan executor error during findAndModify :: caused by :: Cannot apply $addToSet to non-array field. Field named 'permissions' has non-array type string' on server localhost:27017. The full response is {\"ok\": 0.0, \"errmsg\": \"Plan executor error during findAndModify :: caused by :: Cannot apply $addToSet to non-array field. Field named 'permissions' has non-array type string\", \"code\": 2, \"codeName\": \"BadValue\"}");
    }
}
```

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/76812421/170472741-40e5a3f7-3d56-4830-bea3-976a453d351d.png">

[demo.zip](https://github.com/microsoft/vscode-java-test/files/8778403/demo.zip)

**Comment by jdneo** [comment] 2022-06-04 07:54
Tested it in VS Code `1.67.2` with Test Runner `0.35.0` but could not repro this issue. Is there anything I missed?

![image](https://user-images.githubusercontent.com/6193897/171990246-93fcb27e-a001-4733-94bd-9c16da55cc98.png)
![image](https://user-images.githubusercontent.com/6193897/171990261-e06c6777-38d3-49f2-95b3-99ad65ba893b.png)

**Comment by matter-it-does** [comment] 2022-06-06 08:12
Oh caused due to https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one

Please close the report if you deem it right.

**Comment by jdneo** [comment] 2022-06-06 08:20
Thank you for the information. So I'm going to close the issue now since it's caused by other extension. :)

**Closed by jdneo** 2022-06-06 08:20 UTC
Labels: need more info
