### ISSUE TITLE
Adding watches/Evaluating expressions fails during debug

### ISSUE THREAD

**Issue by goncealex** [Microsoft/vscode-java-test#102] opened 2018-01-21 19:00 UTC
Running a test in debug mode and evaluating and/or adding watches to expressions fails with the error:
`Please specify projectName in launch.json.`

Expected Behavior:
1. Add a breakpoint anywhere in the test method
2. Press "Debug Test" link
3. Evaluate or add a watch on an expression 
4. View the result value of the expression

**Comment by goncealex** [comment] 2018-01-21 19:11
If someone can confirm this behavior as a bug, i can create a pull request which should solve the problem.

**Comment by yaohaizh** [comment] 2018-01-22 06:20
@goncealex  This is related to the PR for auto detect the project name: https://github.com/Microsoft/java-debug/pull/146. 

For you now, you can specify the projectname in the launch.json. 

And PR to specific the projectName is welcome.

**Comment by ansyral** [comment] 2018-02-09 06:51
@goncealex https://github.com/Microsoft/java-debug/pull/146 only resolves project name when test name is not duplicate in multiple projects. A better way i think it is to support test configuration where user could configure their test project, what do you think about this?

**Comment by ansyral** [comment] 2018-04-03 06:36
This should work now in the latest version of the extension, @goncealex would you like to have a try?

**Comment by goncealex** [comment] 2018-04-07 13:11
Hi @ansyral ,
i did few tests and it works great! Thanks for the feature!
I tried it few days ago and couldn't find the configurations for all the projects in my workspace, but now it works! ( i guess it was some problem with my setup )

One little thing: if i don't choose a project to test, i get 2 notifications saying "Please specify the test config to use **!**" ( one with exclamation mark at the end and the other one without )

**Comment by ansyral** [comment] 2018-04-13 07:12
@goncealex thanks for your test and feedback! Seems the notification behavior of vscode between debugging and normal usage are different, will fix it.

**Comment by ansyral** [comment] 2018-04-13 07:18
@goncealex I added an issue #165 to track the notification bug, so I'm gonna close this one.

**Comment by RuiffCardoso** [comment] 2018-08-22 09:13
I'm still receiving the same issue when individually testing a sub-project of a main project. I'm not sure if this is the issue, but the structure is something like this:

- Main Project
    - .vscode
         - launch.json
         - launch.test.json (contains many entries, including SubProject projectName)
    -  SubProject
          - (no .vscode with launch.json or launch.test.json here)

Versions:
- code @ 1.26.1
- vscjava.vscode-java-debug @ 0.11.0
- vscjava.vscode-java-pack @ 0.3.0
- vscjava.vscode-java-test @ 0.8.0

**Comment by yaohaizh** [comment] 2018-08-23 01:54
@ansyral Reopen it since it is still reproed.

**Comment by ivenxu** [comment] 2018-08-31 07:13
As @RuiffCardoso pointed out,  quick button "Run test | Debug test" it doesn't. It seems "Run With Config" prompt user picking up the config from launch.test.json. But the quick buttons don't prompt the user to select the config. Anyway, I think it's good idea to derive the projectName since the quick buttons are triggered from the source file, it should be able to derive it from the file.

**Comment by jdneo** [comment] 2018-11-09 02:40
@RuiffCardoso @ivenxu  what if you set the `default` field in the `launch.test.json` with the default configuration name you want to run with?

**Comment by RuiffCardoso** [comment] 2018-11-14 10:23
> @RuiffCardoso @ivenxu what if you set the `default` field in the `launch.test.json` with the default configuration name you want to run with?

Setting the default field made it work!

**Comment by jdneo** [comment] 2018-11-15 07:43
Closing since the problem is resolved.

**Closed by jdneo** 2018-11-15 07:43 UTC

**Comment by ivenxu** [comment] 2018-11-21 04:46
@RuiffCardoso could you please share your launch.test.json? 
@jdneo The message I'm getting from the quick buttons "Run test | Debug test" is about launch.json not launch.test.json. Could you tell why launch.json is used here?

**Comment by RuiffCardoso** [comment] 2018-11-26 14:41
> @RuiffCardoso could you please share your launch.test.json?

``` JSON
{
    "run": {
        "default": "",
        "items": [
            {
                "name": "PROJECT_A",
                "projectName": "PROJECT_A",
                "workingDirectory": "d:\\project_folder\\PROJECT_A",
                "args": [],
                "vmargs": [],
                "env": {},
                "preLaunchTask": ""
            },
            {
                "name": "petro-common-utils",
                "projectName": "petro-common-utils",
                "workingDirectory": "d:\\project_folder\\petro-common-utils",
                "args": [],
                "vmargs": [],
                "env": {},
                "preLaunchTask": ""
            }
        ]
    },
    "debug": {
        "default": "PROJECT_B",
        "items": [
            {
                "name": "PROJECT_A",
                "projectName": "PROJECT_A",
                "workingDirectory": "d:\\project_folder\\PROJECT_A",
                "args": [],
                "vmargs": [],
                "env": {},
                "preLaunchTask": ""
            },
            {
                "name": "PROJECT_B",
                "projectName": "PROJECT_B",
                "workingDirectory": "d:\\project_folder\\PROJECT_B",
                "args": [],
                "vmargs": [],
                "env": {},
                "preLaunchTask": ""
            }
        ]
    }
} 
```

One thing I would like to had is that if I had these difficulties, maybe this should be an improvement point.

**Comment by ivenxu** [comment] 2018-11-27 09:19
Thanks for sharing!

One more question: How it works for the tests in PROJECT_A though?

> > @RuiffCardoso could you please share your launch.test.json?
> 
> ```json
> {
>     "run": {
>         "default": "",
>         "items": [
>             {
>                 "name": "PROJECT_A",
>                 "projectName": "PROJECT_A",
>                 "workingDirectory": "d:\\project_folder\\PROJECT_A",
>                 "args": [],
>                 "vmargs": [],
>                 "env": {},
>                 "preLaunchTask": ""
>             },
>             {
>                 "name": "petro-common-utils",
>                 "projectName": "petro-common-utils",
>                 "workingDirectory": "d:\\project_folder\\petro-common-utils",
>                 "args": [],
>                 "vmargs": [],
>                 "env": {},
>                 "preLaunchTask": ""
>             }
>         ]
>     },
>     "debug": {
>         "default": "PROJECT_B",
>         "items": [
>             {
>                 "name": "PROJECT_A",
>                 "projectName": "PROJECT_A",
>                 "workingDirectory": "d:\\project_folder\\PROJECT_A",
>                 "args": [],
>                 "vmargs": [],
>                 "env": {},
>                 "preLaunchTask": ""
>             },
>             {
>                 "name": "PROJECT_B",
>                 "projectName": "PROJECT_B",
>                 "workingDirectory": "d:\\project_folder\\PROJECT_B",
>                 "args": [],
>                 "vmargs": [],
>                 "env": {},
>                 "preLaunchTask": ""
>             }
>         ]
>     }
> } 
> ```
> 
> One thing I would like to had is that if me and other people (#436 for example), maybe this should be one improvement point.

**Comment by ivenxu** [comment] 2018-11-27 09:31
> @ivenxu just change the value of `default` can work.
> 
> For example, you want to enable the config item with name `PROJECT_A`, just set the value of `default` to `PROJECT_A`

@jdneo , sorry I don't quite follow your idea. Are you saying when I Debug Test in the Code Lens for tests in project A I set the default to 'PROJECT_A'. And switch to 'PROJECT_B' when debuging test for project B?

**Comment by jdneo** [comment] 2018-11-27 10:31
@ivenxu Yes, correct.

**Comment by ivenxu** [comment] 2018-11-27 10:37
> @ivenxu Yes, correct.

Thanks for clarifying this! However, it's not convenient and it defeats the purpose of having "Debug Test" as Code Lens. If possible, can we have an enhancement to derive the product name information from the location of the source code?

**Comment by RuiffCardoso** [comment] 2018-11-27 11:10
> One more question: How it works for the tests in PROJECT_A though?

The code runs and the breakpoint works, but writing an expression that uses current context variables gives the following error:
`Cannot evaluate because of compilation error(s): Evaluations must contain either an expression or a block of well-formed statements.`

**Comment by jdneo** [comment] 2018-11-28 01:32
@ivenxu The current experience of `run/debug with configuration` do have a lot of inconveniences.

Will address this later.
