### ISSUE TITLE
Spring Boot Test Fails with NoSuchBeanDefinitionException.

### ISSUE THREAD

**Issue by ecormaksin** [Microsoft/vscode-java-test#621] opened 2018-12-24 07:09 UTC
Any advice would be appreciated.

[provide a description of the issue]

##### Environment
- Operating System: macOS High Sierra 10.13.6
- JDK version: 1.8.0_151
- Visual Studio Code version: 1.30.1
- Java extension version: 0.5.0
- Java Debugger extension version: 0.16.0

##### Steps To Reproduce
1. Create Spring Boot project by following the page below. https://code.visualstudio.com/docs/java/java-spring-boot
2. Write test code with annotations below.
`@RunWith(SpringRunner.class)`
`@SpringBootTest`
`@ContextConfiguration(classes = BatchTestConfig.class)`
3. Run the test.

[attach a sample project reproducing the error]
[2018-12-24_TestReport.log](https://github.com/Microsoft/vscode-java-debug/files/2706758/2018-12-24_TestReport.log)

##### Current Result

NoSuchBeanDefinitionException occurs. But the test finishes with green on the Eclipse IDE.

##### Expected Result

The test finishes with green(passed).

**Comment by jdneo** [comment] 2019-02-25 06:47
Hi @ecormaksin,

Thank you for reporting the issue and give us the sample project. After some investigation, I think I might found out the root cause.

The root cause is that when the extension running the tests, it will read the `application.properties` under the target folder. But the content of it is the same as that in the `src` (not the one in `test`). After I copied the `application.properties` in the `test` to the `target` folder, the test cases can be run successfully.

This issue might be related to #534 

I'll think about how to make a fix and let you know.

Thank you.

**Comment by jdneo** [comment] 2019-02-25 07:15
More investigation result here: https://github.com/Microsoft/vscode-java-test/issues/534#issuecomment-466897041

**Comment by jdneo** [comment] 2019-02-26 06:34
Closing this issue and let's track it in #534

**Closed by jdneo** 2019-02-26 06:34 UTC

**Comment by ecormaksin** [comment] 2019-04-03 11:35
I apoligize for too late reply. Thank you so much!
