### ISSUE TITLE
Problem with debugging

### ISSUE THREAD

**Issue by kpodsiad** [microsoft/vscode-java-test#1330] opened 2021-11-04 07:22 UTC
Hey!
I wanted to play with the java-test extension, but If I run the extension in debug mode it fails during resolving tests at the `loadJavaProjects()` function. However, when I open my test project with plain (not debugging) vs code, it just works.

I wonder what would be the best way to debug what's happening, does Java Language Server have logs somewhere?

```shell
Version: 1.61.2 (Universal)
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T15:49:28.381Z (2 wks ago)
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
```

**Comment by jdneo** [comment] 2021-11-04 07:31
Can you provide the errors when you run it in debug mode? You can find them via the command `Java：Open Java Language Server Log File`

BTW, there is a document about how to setup the dev env: https://github.com/microsoft/vscode-java-test/blob/main/CONTRIBUTING.md#setup
After installing PDE, right click on this file: https://github.com/microsoft/vscode-java-test/blob/main/java-extension/com.microsoft.java.test.plugin/target.target and select `reload target platform`

**Comment by kpodsiad** [comment] 2021-11-04 07:53
Ok, I found something interesting in logs
`java.nio.file.NoSuchFileException: /Users/kpodsiadlo/***/vscode-java-test/server/com.microsoft.java.test.plugin-0.32.0.jar`

I guess I'll have to run `npm run build-plugin` to build the missing plugin JAR.

But I wonder what caused these issues, I started playing with the java-test in October and everything was working just after `npm install`. I didn't do anything tricky in the meantime 🤔

**Comment by jdneo** [comment] 2021-11-04 08:20
Not sure what happened. But I can confirm that `npm run build-plugin` is required. 😀

**Comment by jdneo** [comment] 2021-11-04 08:38
I'm closing this issue since it looks like the problem is solved.

Feel free to leave comments if there are any other problems for debugging the extensions.

**Closed by jdneo** 2021-11-04 08:38 UTC

**Comment by kpodsiad** [comment] 2021-11-04 08:52
Everything works like a charm, thanks @jdneo!
