### ISSUE TITLE
sunrsasign.jar issue while debugging

### ISSUE THREAD

**Issue by sayonsur** [microsoft/vscode-java-test#804] opened 2019-09-11 09:33 UTC
I am not able to debug any test. Getting following error. it might have to do something with Java versions.
_"Exception has occurred: java.io.FileNotFoundException
"java.io.FileNotFoundException: \D:\ojdkbuild\java-1.8.0-openjdk-1.8.0.91-3\jre\lib\sunrsasign.jar""_

As you see i am using OpenJdk. As per the details i can find this class is present in rt.jar in JRE now.
https://stackoverflow.com/questions/15885401/where-can-i-get-an-official-copy-of-sunrsasign-jar

Any suggestions how to fix this in VSCode.

**Comment by jdneo** [comment] 2019-09-12 04:48
Hi @sayonsur,

Thank you for reporting the issue. I might need more information to check why the test runner will seek for this jar. Is it possible to provide a repro step about this issue?

**Comment by sayonsur** [comment] 2019-09-12 07:38
It's happening for me whenever i am trying to debug. it's coming from accesscontroller class .
I also get the other pop up frequently. Maybe something to do with project set up. see the attachments.
![error1](https://user-images.githubusercontent.com/20788069/64763691-2a9bb380-d55e-11e9-972b-d2b6a27153a5.JPG)
![exception](https://user-images.githubusercontent.com/20788069/64763705-34bdb200-d55e-11e9-86e8-79fc9f8e4ae9.JPG)

**Comment by jdneo** [comment] 2019-09-16 05:37
@sayonsur Is it possible to provide a project which can repro this issue to us?

**Comment by alan-hwp** [comment] 2019-10-16 09:50
Hi,
I'm afraid to report I get the exactly the same error when debugging. It emanates from 

URLClassPath.class (Line 938) from adoptOpenJDK1.8.0_222. (package sun.misc;)

[Exception has occurred: java.io.FileNotFoundException
"java.io.FileNotFoundException: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/sunrsasign.jar"] 

Obviously I am using a Mac - OS version: Mojave 10.14.3

I am using Code-Insiders version 1.40;
Debugger for Java version: 0.22.0
Language support for Java (RH) 0.50.0

The invocation that causes the exception is:
void com.amazonaws.services.s3.transfer.Transfer.waitForCompletion() throws AmazonClientException, AmazonServiceException, InterruptedException
....

**Comment by jdneo** [comment] 2019-10-16 10:14
@alan-hwp Have you check the `Caught Exceptions` in the breakpoints panel?

**Comment by alan-hwp** [comment] 2019-10-16 12:32
Hi @jdneo,
Thanks for your quick reply. Yes, I do have that checked in the breakpoints panel.

**Comment by jdneo** [comment] 2019-10-17 03:29
@alan-hwp Though I have no idea why this exception is generated, but I guess your problem could be resolved if you uncheck the `Caught Exceptions`.

**Comment by rafaelbdb** [comment] 2019-10-18 10:34
As @jdneo said, unchecking `Caught Exceptions` solves it (if you use `Debug Test` - using `Run Test` works even with that option checked).

**Comment by jdneo** [comment] 2019-10-18 11:46
@rafaelbdb As far as I know, this is not a bug. Just as the options says, this is a caught exception. During a program is running, you can observe that there will be different kinds of exceptions being caught(depend on your implementation).

Anyway, it will be better if I can get a sample project which can repro this problem, otherwise, it's hard to say if this is a bug or not.

**Comment by alan-hwp** [comment] 2019-10-18 12:24
Hi, please accept my apologies. I do not (yet) understand why that exception is thrown, but I did un-check both caught / uncaught exceptions, in the breakpoints panel, and that allowed me to debug as I expected. Thanks for you input. @rafaelbdb @jdneo. Perhaps the on-line docs might be expanded, to inform (Java) VS Code users to un-check the breakpoint check boxes?

**Comment by jdneo** [comment] 2019-10-19 03:47
@alan-hwp Thank you for your advice. Yes, I think after we understand why this exception is thrown, then we can add related information to the docs.

I'll close this issue for now since it seems that this is not a bug. Thank you all for your participation.

**Closed by jdneo** 2019-10-19 03:47 UTC
Labels: need more info

**Comment by oymh0** [comment] 2022-09-01 09:27
thanks a lot I use ctrl + shift + F8 to unselect all then it worked.

**Comment by brucecui1998** [comment] 2024-01-23 01:08
problem is solved in [here](https://stackoverflow.com/questions/15885401/where-can-i-get-an-official-copy-of-sunrsasign-jar)

**Comment by oymh0** [comment] 2024-01-23 01:09
Thank you for mailing Minghui(Fiona) OUYANG, she will reply as soon as possible.
