### ISSUE TITLE
Doesn't work with Parameterized

### ISSUE THREAD

**Issue by dsyer** [Microsoft/vscode-java-test#35] opened 2017-12-01 19:31 UTC
```java
package com.example.demo;

import java.util.Arrays;
import java.util.List;

import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.runners.Parameterized.Parameters;

@RunWith(Parameterized.class)
public class ParamTests {

    @Parameters
	public static List<Object[]> parameters() {
        return Arrays.asList(new Object[] {"foo"}, new Object[] {"bar"});
    }

   public ParamTests(String value) {}

   @Test
   public void test() {
   }
}
```

Click on "Run Test" on the class level and it runs them, but no status is available. And actually, if the test fails, it's just the same (status is a big "?").

Click on "Run Test" (on the `@Test`). Result:

```
@@<{"name":"testReporterAttached"}>
@@<{"name":"rootName", "attributes":{"name":"Default Suite"}}>
@@<{"name":"suiteTreeStarted", "attributes":{"name":"org.junit.runner.manipulation.Filter", "location":"java:test://org.junit.runner.manipulation.Filter"}}>
@@<{"name":"suiteTreeNode", "attributes":{"name":"initializationError", "location":"java:test://org.junit.runner.manipulation.Filter.initializationError"}}>
@@<{"name":"suiteTreeEnded", "attributes":{"name":"org.junit.runner.manipulation.Filter", "location":"java:test://org.junit.runner.manipulation.Filter"}}>
@@<{"name":"testSuiteStarted", "attributes":{"name":"org.junit.runner.manipulation.Filter", "location":"java:test://org.junit.runner.manipulation.Filter"}}>
@@<{"name":"testStarted", "attributes":{"name":"initializationError", "location":"java:test://org.junit.runner.manipulation.Filter.initializationError"}}>
@@<{"name":"testFailed", "attributes":{"name":"initializationError", "message":"No tests found matching Method test(com.example.demo.ParamTests) from org.junit.internal.requests.ClassRequest@5b80350b", "details":"java.lang.Exception: No tests found matching Method test(com.example.demo.ParamTests) from org.junit.internal.requests.ClassRequest@5b80350b\n\tat org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:40)\n\tat com.microsoft.java.test.runner.TestRunnerUtil.getRequestForOneMethod(TestRunnerUtil.java:50)\n\tat com.microsoft.java.test.runner.TestRunnerUtil.createTestReferences(TestRunnerUtil.java:38)\n\tat com.microsoft.java.test.runner.CustomizedJUnitCoreRunner.run(CustomizedJUnitCoreRunner.java:26)\n\tat com.microsoft.java.test.runner.JUnitLauncher.main(JUnitLauncher.java:21)\n", "duration":"1"}}>
@@<{"name":"testFinished", "attributes":{"name":"initializationError", "duration":"2"}}>
@@<{"name":"testSuiteFinished", "attributes":{"name":"org.junit.runner.manipulation.Filter"}}>
Total tests run: 1, Failures: 1, Skips: 0
```

**Comment by ansyral** [comment] 2017-12-19 08:19
To support `parameterized`, it need much more work than I expected before and we need to redesign how to show the test's status in codelens and test explorer since it is a compound status for parameterized case. 
Move this to next milestone.

**Comment by ansyral** [comment] 2018-02-26 07:12
duplicate of #107

**Closed by ansyral** 2018-02-26 07:12 UTC
Labels: bug
