### ISSUE TITLE
Java Test Report results won't expand

### ISSUE THREAD

**Issue by inewland53** [microsoft/vscode-java-test#984] opened 2020-04-25 13:10 UTC
After running a java test, the Java Test Report window immediately opens and I am not able to expand the result(s).

From time to time I am able to get it to expand but the result vary. Sometime I can restart VS Code, run my test and it will allow me to expand the test result. However, I would say I cannot expand it more than I can.

I've attached a screenshot of the test window and the VS Code version.

![Screenshot from 2020-04-25 09-06-45](https://user-images.githubusercontent.com/7481506/80280764-275fcd00-86d4-11ea-8a67-46d1314754f2.png)

![image](https://user-images.githubusercontent.com/7481506/80280747-00090000-86d4-11ea-9c1c-25d7a37c6d0a.png)

**Comment by sameerbo** [comment] 2020-04-26 05:21
Yes facing the exactly the same issue.

**Comment by jdneo** [comment] 2020-04-26 05:26
Hi @ZhengJun003,

Could you please help verify this issue on Linux env?

**Comment by ZhengJun003** [comment] 2020-04-27 09:08
Hi @jdneo, Cannot repro on Linux env

**Environment:** 
```
OS: Ubuntu 16.04
VS Code: 1.44.2
Java Test Runner: 0.22.3
Debugger for Java: 0.25.1
Language Support for Java by Red Hat: 0.60.0
```

**Result:**
- Junit4: [todo-app-java-on-azure](https://github.com/bsaby/todo-app-java-on-azure/tree/testrunner)
  ![image](https://user-images.githubusercontent.com/41051257/80351893-a5bf9900-88a5-11ea-8804-5e3a54ccd46e.png)

- Junit5: [junit5-samples](https://github.com/ZhengJun003/junit5-samples/tree/testrunner)
  - junit5-jupiter-starter-maven    
    ![image](https://user-images.githubusercontent.com/41051257/80352423-752c2f00-88a6-11ea-9b52-277c27082e3a.png)

  - junit5-migration-gradle
    ![image](https://user-images.githubusercontent.com/41051257/80353617-2f706600-88a8-11ea-8950-f1ee649df3df.png)

- TestNG: [TestNG-Spring-Example](http://www.mkyong.com/wp-content/uploads/2014/01/TestNG-Spring-Example.zip)
  ![image](https://user-images.githubusercontent.com/41051257/80354585-83c81580-88a9-11ea-9659-56eb4b03adf3.png)

**Comment by inewland53** [comment] 2020-04-28 22:38
I wanted to post a little more information. I haven't been able to explicitly create a simple scenario where I can reproduce this but I have an example i'm working with in my current project.

I made an integration test that calls an internal REST Controller internally using this code snippet:
![image](https://user-images.githubusercontent.com/7481506/80544340-d58e9f80-897e-11ea-9c61-6312026a92d1.png)

I received a 500 Server Error against that and received a lofty Stack Trace:
![image](https://user-images.githubusercontent.com/7481506/80544428-0b338880-897f-11ea-91d2-3dc16dae0d57.png)

Immediately the Java Test Report window opens and I cannot expand it:
![image](https://user-images.githubusercontent.com/7481506/80544477-24d4d000-897f-11ea-87fc-8405a385da37.png)

It appears to always open if I receive a 200 success with my integration test:
![image](https://user-images.githubusercontent.com/7481506/80544594-5fd70380-897f-11ea-9de3-2b2d44fc8e71.png)

Maybe this will help hunt down the issue!?

This is a Java Maven project using Spring Boot, Web Reactive Starter.

**Comment by jdneo** [comment] 2020-04-29 01:49
Could you try to set the setting `java.test.log.level` to `verbose`.

Then you could toggle to the Test Runner output channel to see if there is any suspicious output?
![image](https://user-images.githubusercontent.com/6193897/80554114-aa4b9500-89fe-11ea-88f7-ca5ad1424335.png)


Especially for the failed one: `io.fe.organization.OrganizationTests.post`

**Comment by inewland53** [comment] 2020-04-29 21:48
Ok I was able to get some information out of the Output. I've attached the 2 files. I couldn't see anything crazy that stood out but maybe you can take a quick look and compare.
[failed.txt](https://github.com/microsoft/vscode-java-test/files/4554797/failed.txt)
[success.txt](https://github.com/microsoft/vscode-java-test/files/4554798/success.txt)

**Comment by jdneo** [comment] 2020-04-30 06:31
I reproduced this bug today. And I saw the following error message in the webview developer tools' console:

`Uncaught ReferenceError: $ is not defined`, which I guess it means the JQuery is not loaded successfully.

A workaround is to close the test report and reopen it by clicking the item in the status bar:
<img width="1031" alt="Screen Shot 2020-04-30 at 2 30 51 PM" src="https://user-images.githubusercontent.com/6193897/80679341-4654c980-8aef-11ea-97f0-9047fdc5b157.png">

**Comment by ShadowLNC** [comment] 2020-05-02 08:57
Thanks for the workaround - confirmed that is viable for me as a stop-gap.
I can reproduce the issue on Windows (and I also see the JQuery error):
```
Version: 1.44.2 (user setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by w3aponx** [comment] 2020-05-05 20:23
Hi @jdneo, just wanted to let you know this happens under Linux as well.  Running Ubuntu 16.04 here. I can confirm that the workaround works also on Linux (thanks for that!).

**Comment by GuillaumeDesforges** [comment] 2020-05-28 14:48
Same hapenning (sorry for the duplicate btw).

Suggeseted workaround does not work for me.

Also I get
```
[Embedded Page] Uncaught ReferenceError: $ is not defined
``` 

Everytime I open the panel

**Comment by jdneo** [comment] 2020-05-29 02:36
Hey @GuillaumeDesforges,

Thank you for providing such great diagnostic information. That's interesting, seems something that we do not handled correctly in a certain scenario. Could you provide more information about how you encounter this problem? To help me repro this issue, like:

- Are you in a local environment or a browser/remote environment?
- Is is possible to provide some screenshots, gifs are better.

**Comment by GuillaumeDesforges** [comment] 2020-05-29 08:22
VSCode 1.46.0-inside

I'm using the remote SSH plugin, and work through SSH on a remote server on NixOS 20.03 (don't think that the remote OS is the cause though).

I have run a test, cleaned the Console (Ctrl+L), opened the panel using the button in the status bar. Here is said result (not sure it adds much to previous descriptions).

![image](https://user-images.githubusercontent.com/1882000/83237985-089e9b80-a196-11ea-97de-4cbf80fc0d86.png)

**Comment by GuillaumeDesforges** [comment] 2020-05-29 08:23
Seems related to https://github.com/microsoft/vscode/issues/72900

**Comment by GuillaumeDesforges** [comment] 2020-05-29 08:30
I suspect it comes from the way the Remote SSH plugin distribute files like a server, see https://github.com/microsoft/vscode-remote-release/issues/3076

**Comment by afonsobaco** [comment] 2020-05-31 14:38
Same problem here, the workaround worked on linux environment

the problem occurs in both failed and successful cases.

**Comment by jdneo** [comment] 2020-06-01 01:43
@GuillaumeDesforges thanks!

Let's wait to see if there is any update in the upstream issue.

**Comment by qzmarco** [comment] 2020-07-31 13:49
Same problem here. It happens sometimes... I am using Ubuntu 20.04 via WSL 2 on Windows 10 2004 version.

**Comment by jdneo** [comment] 2020-10-14 03:06
Does this problem still occur?

**Comment by GuillaumeDesforges** [comment] 2020-10-14 10:26
Not doing Java anymore rn :/

**Comment by cvandermeer** [comment] 2020-10-21 06:59
I am running SWL on windows 10 with ubuntu 20.04 as well and i have the exact same problem

**Comment by djkong7** [comment] 2020-11-03 21:34
I'm also on running Ubuntu 20.04 on WSL 2 on Windows 10 and have the same issue. Also have the same error:
"[Embedded Page] Uncaught ReferenceError: $ is not defined"
and the workaround of closing and reopening using the status bar doesn't work.

**Comment by RationalPi** [comment] 2021-04-26 15:29
I have the same problem. Running on macOS Catalina (Version 10.15.7) with vscode 1.55.1 with a Java Dev Container (mcr.microsoft.com/vscode/devcontainers/java:0-15). Closing the Java Test Report and reopening it seems to fix it - at least temporarily.

The output for Java Test Running contains the following over and over again: "Error: Running the contributed command: 'java.execute.workspaceCommand' failed..Failed to provide Code Lens."

**Comment by jdneo** [comment] 2021-08-06 02:38
In 0.31.0, we support the newest VS Code testing API in 1.59.0. The test report is removed so I'll close this issue

**Closed by jdneo** 2021-08-06 02:38 UTC
Labels: bug
