### ISSUE TITLE
Get 'NoSuchMethodError' when using TestNG 7

### ISSUE THREAD

**Issue by klubi** [microsoft/vscode-java-test#909] opened 2019-12-22 21:59 UTC
When I try to run tests with TestNG 7.0.0 I get below exception.

```
[Warn  - 10:57:22 PM] Dec 22, 2019, 10:57:22 PM Cannot collect dependency scope information for launch configuration JUnit Launch Configuration
No tests found with test runner 'JUnit 3'.
org.eclipse.core.runtime.CoreException: No tests found with test runner 'JUnit 3'.
	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate.abort(JUnitLaunchConfigurationDelegate.java:752)
	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate.evaluateTests(JUnitLaunchConfigurationDelegate.java:361)
	at org.eclipse.buildship.core.internal.launch.SupportedLaunchConfigType$RelaxedJUnitLaunchConfigurationDelegate.evaluateTests(SupportedLaunchConfigType.java:139)
	at org.eclipse.buildship.core.internal.launch.SupportedLaunchConfigType$2.getSourceFolders(SupportedLaunchConfigType.java:70)
	at org.eclipse.buildship.core.internal.launch.SupportedLaunchConfigType.collectSourceFolders(SupportedLaunchConfigType.java:110)
	at org.eclipse.buildship.core.internal.launch.LaunchConfigurationScope.from(LaunchConfigurationScope.java:57)
	at org.eclipse.buildship.core.internal.workspace.GradleClasspathContainerRuntimeClasspathEntryResolver.resolveRuntimeClasspathEntry(GradleClasspathContainerRuntimeClasspathEntryResolver.java:53)
	at org.eclipse.jdt.internal.launching.RuntimeClasspathEntryResolver.resolveRuntimeClasspathEntry(RuntimeClasspathEntryResolver.java:49)
	at org.eclipse.jdt.launching.JavaRuntime.resolveRuntimeClasspathEntry(JavaRuntime.java:1262)
	at org.eclipse.jdt.launching.StandardClasspathProvider.resolveClasspath(StandardClasspathProvider.java:95)
	at org.eclipse.jdt.launching.JavaRuntime.resolveRuntimeClasspath(JavaRuntime.java:1657)
	at com.microsoft.java.test.plugin.launchers.JUnitLaunchUtils.resolveTestNGLaunchArguments(JUnitLaunchUtils.java:161)
	at com.microsoft.java.test.plugin.launchers.JUnitLaunchUtils.resolveLaunchArgument(JUnitLaunchUtils.java:93)
	at com.microsoft.java.test.plugin.handler.TestDelegateCommandHandler.executeCommand(TestDelegateCommandHandler.java:48)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:213)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:203)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:463)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$45(JDTLanguageServer.java:936)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

Setup:
MacOS Catalina
VS Code Version: 1.41.1
Gradle 6.0.1
Java 11
TestNG 7.0.0

**Comment by jdneo** [comment] 2020-01-02 02:36
Hi @klubi,

Would you mind to share a sample project which can repro this issue to us? I could not repro this issue locally.

Thanks.

**Comment by klubi** [comment] 2020-01-02 10:57
Sure thing @jdneo, I left `.code` and other project files.
https://github.com/klubi/vsc-testng7-sample

**Comment by jdneo** [comment] 2020-01-03 09:04
Hi @klubi 

Thank you for providing the sample project. I run it locally from my side but get a different error:

`java.lang.NoSuchMethodError: org.testng.TestNG.addListener(Lorg/testng/ITestListener;)`

Though I can fix that issue in another PR. But I'm still not able to reproduce this one:

`Cannot collect dependency scope information for launch configuration JUnit Launch Configuration`

What's the Test Runner version are you using?

BTW, still want to thank you for let us know that we have some issue with TestNG 7 supporting.

Thanks

**Comment by klubi** [comment] 2020-01-03 14:30
@Jdneo I'm on 0.22.0, and 0.8.1 version of Java Extension Pack

![image](https://user-images.githubusercontent.com/4123293/71728594-d171cb80-2e3d-11ea-887e-236016a729e1.png)

**Comment by jdneo** [comment] 2020-01-06 05:19
Hmm,

Will you get the same error: `Cannot collect dependency scope information for launch configuration JUnit Launch Configuration` if you downgrade the TestNG to ... like `6.13`?

**Comment by klubi** [comment] 2020-01-07 09:26
Weird... I wanted to screen record running tests with testNG 7.0.1, then switch back to 6.13 and run them again... but now I'm getting that `NoSuchMethodError`.
Let me wait for `0.22.1`. and see if this will solve this issue.

**Comment by jdneo** [comment] 2020-01-08 02:38
Hi @klubi,

Thank you for your feedback. If it's `NoSuchMethodError`, I'm closing this issue for now since the [PR](https://github.com/microsoft/vscode-java-test/pull/916) has been fixed that.

But If you still meet the problem after the new version gets released, please just re-open the issue and let me know. :)

Thank you.

**Closed by jdneo** 2020-01-08 02:38 UTC
Labels: bug
