### ISSUE TITLE
Error: Failed to parse the JUnit launch arguments

### ISSUE THREAD

**Issue by lydo1797** [microsoft/vscode-java-test#936] opened 2020-02-13 09:06 UTC
### Environment:
* OS: MacOS
* JDK: 1.8.0_212
### Java Extension:
* Language Support for Java(TM) by Red Hat: 0.55.1
* Debugger for Java: 0.24.0
* Java Test Runner: 0.22.1

![image](https://user-images.githubusercontent.com/32587882/74418334-1570cc80-4dfd-11ea-921e-54dd898eabf4.png)

**Comment by jdneo** [comment] 2020-02-13 09:24
Thank you @lydo1797,

Is it possible for you to share a sample project which can repro this issue to us?

**Comment by lydo1797** [comment] 2020-02-13 09:27
Here's the zip file for my project: [ly.zip](https://github.com/microsoft/vscode-java-test/files/4197453/ly.zip)

**Comment by jdneo** [comment] 2020-02-13 09:37
The problem is that the `.classpath` file does not configure correctly.

Here is a suggestion:

1. Close VS Code
2. In your project folder `ly`, remove all the file and folders **except** `lib/` and `src/`
3. You will also need download [this jar](https://mvnrepository.com/artifact/org.junit.platform/junit-platform-console-standalone/1.6.0) to complete the required library
4. Now, open the folder `ly` in VS Code

**Comment by lydo1797** [comment] 2020-02-13 09:40
Using the stand-alone jar suggested above works for me!

Can you please tell me only this stand-alone jar works?

**Comment by jdneo** [comment] 2020-02-13 10:26
It contains the required classes which are needed to run the JUnit5's tests.

**Comment by jdneo** [comment] 2020-02-14 01:42
Closing this issue since the problem seems solved.

But feel free to let me know if you have any more questions.

**Closed by jdneo** 2020-02-14 01:42 UTC

**Comment by huachangYu** [comment] 2020-09-25 00:48
you need new version of junit. My codes work well when the version of junit is 4.13 but we encountered same issue as you describe : )

**Comment by nikhilmaddirala** [comment] 2020-10-07 03:32
Hi, I'm facing the exact same problem even though I'm using the standalone jar (junit-platform-console-standalone-1.7.0-all.jar). Here's the [repo](https://github.com/nikhilmaddirala-mcit/594-m4) for my project. I have several similar projects with the same structure where I don't run into this error, so I'm not sure why I'm getting this error now! :/

Thanks in advance for any help!

**Comment by jdneo** [comment] 2020-10-10 02:23
Hi @nikhilmaddirala I tried your repo (594-m6) and it works well on my side. (Running the test `BinarySearchTreeTest#testFindNode()`)

Could you try to trigger the command: `Java: Clean the Java language server workspace` to see if it helps?

**Comment by nikhilmaddirala** [comment] 2020-10-12 17:26
Hi @jdneo : Thank you for your reply! [Per this screenshot](https://imgur.com/a/WudhT4L), individual tests (green arrow) are running fine, but "run all tests" (red arrow) results in this error, and cleaning the Java language server workspace is not helping unfortunately! Any idea why this may be happening?

**Comment by jdneo** [comment] 2020-10-13 02:06
@nikhilmaddirala

Change `import org.junit.Test;` to `import org.junit.jupiter.api.Test;` should solve the problem

**Comment by nikhilmaddirala** [comment] 2020-10-13 18:51
@jdneo : Problem solved, thank you so much! 😄
