### ISSUE TITLE
Unable to setup in development mode

### ISSUE THREAD

**Issue by rohinwork** [microsoft/vscode-java-test#706] opened 2019-05-17 06:41 UTC
I am not able to setup Codelens and the Test explorer view in debug extension mode. 

<img width="442" alt="57842370-f56a9900-77e9-11e9-8d0e-3754c28d11d6" src="https://user-images.githubusercontent.com/50485978/57907664-bac13900-789b-11e9-8e07-8a9c466bbb8f.png">

To Reproduce: 
1. follow instruction for development setup on Contributing page (follow instruction only till step 5)
2. create a new project with [spring initializr](https://start.spring.io/)
3. import this project inside the Extension Development VSCode (after launch the task) 

Note: I do not have any other dependency installed locally (ex: eclipse, etc) unless install by the project internally)

**Comment by jdneo** [comment] 2019-05-17 06:47
Could you provide more information about your project generated by spring initializr?

**Comment by rohinwork** [comment] 2019-05-17 07:04
@jdneo Sorry I did not mention. 
Gradle Project -> Java -> Spring Boot 2.1.5

**Comment by jdneo** [comment] 2019-05-17 07:13
Hmm, that's wired. I cannot repro this on my side. Do you encounter this issue only in dev mode?

**Comment by rohinwork** [comment] 2019-05-17 07:24
Yes, this issue is only encountered in dev mode/if I clone your repo, compile package and install manually in regular vscode. 

I can send you setup this scenario in a machine (linux, ubuntu) which you can RDP to if that's okay with you. I can send you the credentials on the email id shared on your profile page. 

Is that okay? 

By the way, this is my current configuration:
macOS Mojave
node: v8.15.1
npm: 6.7.0

**Comment by jdneo** [comment] 2019-05-17 07:27
@rohinwork Is your local repo updated with the latest commit?

**Comment by rohinrohin** [comment] 2019-05-17 08:00
@jdneo yes I have pulled the latest changes before running the all the tasks mentioned.

**Comment by jdneo** [comment] 2019-05-17 08:28
Ok now I can repro this. The root cause seems lie in here https://github.com/microsoft/vscode-java-test/blob/master/java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/ProjectTestUtils.java#L79

I'll send a PR to fix it later.

**Comment by rohinwork** [comment] 2019-05-17 08:36
@jdneo that's great! 
Let me know if you need anything else from me in the meantime. 

Thank you once again :)

**Comment by jdneo** [comment] 2019-05-17 08:57
Just pushed a fix commit under: https://github.com/microsoft/vscode-java-test/tree/cs/path-issue

Feel free to have a try if you would like to.

Thanks.

**Comment by rohinwork** [comment] 2019-05-17 09:02
@jdneo works perfectly! Thank you 👍

**Comment by rohinwork** [comment] 2019-05-17 09:29
Also is there anything specific that you do besides vsce package to get the `.vsix` extension file?

**Comment by jdneo** [comment] 2019-05-20 03:09
Nothing special. Just:
- npm install
- npm run build-plugin
- vsce package

**Closed** 2019-05-20 05:46 UTC
