### ISSUE TITLE
Cannot switching between editor columns through keyboard shortcut

### ISSUE THREAD

**Issue by rootulp** [microsoft/vscode-java-test#1001] opened 2020-05-20 02:10 UTC
Issue Type: <b>Bug</b>

1. Open a Java project
2. Run the following command: "Java: Run all tests"
3. Focus on the tab "Java Test Report"
4. (optional) drag and drop the "Java Test Report" tab into the normal file explorer tab along with tabs of code.
5. Navigate back and forth between tabs a few times (i.e. Cmd + 1, Cmd + 2)
6. Observe that after selecting the "Java Test Report" tab, VSCode becomes unresponse to subsequent keyboard shorcuts (i.e. selecting a different tab or closing the editor entirely).

Extension version: 0.9.1
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1030NG7 CPU @ 1.10GHz (8 x 1100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.28GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jdneo** [comment] 2020-05-27 10:14
@rootulp Could you explain more about: `Observe that after selecting the "Java Test Report" tab, VSCode becomes unresponse to subsequent keyboard shorcuts (i.e. selecting a different tab or closing the editor entirely).`?

**Comment by rootulp** [comment] 2020-05-28 19:10
Yes. The VSCode java test runner appears to prevent subsequent keyboard shorcuts from working. I can reproduce the issue on my machine but not consistently. It takes some combination of focusing the "Java Test Report" tab and of running the "Java: Run all tests" command.

**Comment by jdneo** [comment] 2020-05-29 02:05
@rootulp I'm suspecting that whether this issue is caused by Test Report view or the general VS Code webview. Because from my understanding, the test report does not do anything that may have impact on the shortcuts. (maybe I'm wrong).

Would you mind to do some more tests to see if other webviews have the same behavior? For example, the VS Code's release note. (You can open it by the command: **Code: Show Release Notes**).

Thank you!

**Comment by rootulp** [comment] 2020-05-29 16:30
I haven't observed the same behavior with any other tabs in VSCode include the Release Notes tab.

**Comment by rootulp** [comment] 2020-06-05 17:23
@jdneo @akaroml can I provide any additional information to help the team make progress here?

**Comment by jdneo** [comment] 2020-06-09 08:38
Thank you @rootulp. What we need is a stable repro steps. Then we can diagnostic the root-cause of the bug.

I'm not sure if I executed the steps you mentioned before correctly, but so far I could not repro it. Maybe a gif would be helpful?

**Comment by jdneo** [comment] 2020-06-16 07:55
@rootulp I can repro it now. Sorry I misunderstood at first. It's switching the column group. I was thinking that we were talking about switching between editors

**Comment by jdneo** [comment] 2020-06-16 08:04
Filed an issue in VS Code repo, let's wait to see the update: https://github.com/microsoft/vscode/issues/100267

**Comment by jdneo** [comment] 2021-02-01 05:22
Update: Duplicated with https://github.com/microsoft/vscode/issues/97992

**Comment by jdneo** [comment] 2021-08-06 02:37
In 0.31.0, we support the newest VS Code testing API in 1.59.0. The test report is removed so I'll close this issue.

**Closed by jdneo** 2021-08-06 02:37 UTC
Labels: bug, upstream
