### ISSUE TITLE
'Failed to run tests' error

### ISSUE THREAD

**Issue by thegabriele97** [Microsoft/vscode-java-test#180] opened 2018-04-27 11:36 UTC
Hi,
I don't know why today Junit seems stopped working..

![image](https://user-images.githubusercontent.com/35406071/39360348-3225ea2a-4a1e-11e8-993b-f561af337a50.png)

You can find my test case and .classpath here
https://gist.github.com/thegabriele97/558bce9ae5e4aff5964e5be009785b64

**Comment by ansyral** [comment] 2018-05-14 06:51
@thegabriele97 seems a strange case. Could you help share logs during that period? You can open the log by invoking the command `Java:Open log` in the command palette.

**Comment by BrightSoul** [comment] 2018-06-22 07:59
I cannot run tests either. Here's my log.
```
{"sessionId":"70ba0473-1d18-4082-a26a-d42ae8152046","level":"error","message":"Error occurred: Exception in thread \"main\" ","timestamp":"2018-06-22T07:52:04.742Z"}
{"sessionId":"70ba0473-1d18-4082-a26a-d42ae8152046","level":"error","message":"Error occurred: java.lang.NoClassDefFoundError: org/junit/runner/JUnitCore\r\n","timestamp":"2018-06-22T07:52:04.742Z"}
{"sessionId":"70ba0473-1d18-4082-a26a-d42ae8152046","level":"error","message":"Error occurred: \tat java.lang.ClassLoader.defineClass1(Native Method)\r\n\tat java.lang.ClassLoader.defineClass(ClassLoader.java:763)\r\n\tat java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)\r\n\tat java.net.URLClassLoader.defineClass(URLClassLoader.java:467)\r\n\tat java.net.URLClassLoader.access$100(URLClassLoader.java:73)\r\n\tat java.net.URLClassLoader$1.run(URLClassLoader.java:368)\r\n\tat java.net.URLClassLoader$1.run(URLClassLoader.java:362)\r\n\tat java.security.AccessController.doPrivileged(Native Method)\r\n\tat java.net.URLClassLoader.findClass(URLClassLoader.java:361)","timestamp":"2018-06-22T07:52:04.744Z"}
{"sessionId":"70ba0473-1d18-4082-a26a-d42ae8152046","level":"error","message":"Error occurred: \r\n\tat java.lang.ClassLoader.loadClass(ClassLoader.java:424)\r\n\tat sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)\r\n\tat java.lang.ClassLoader.loadClass(ClassLoader.java:357)\r\n\tat com.microsoft.java.test.runner.JUnitLauncher.main(JUnitLauncher.java:20)\r\nCaused by: java.lang.ClassNotFoundException: org.junit.runner.JUnitCore\r\n\tat java.net.URLClassLoader.findClass(URLClassLoader.java:381)\r\n\tat java.lang.ClassLoader.loadClass(ClassLoader.java:424)\r\n\tat sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)\r\n\tat java.lang.ClassLoader.loadClass(ClassLoader.java:357)\r\n\t... 13 more\r\n","timestamp":"2018-06-22T07:52:04.744Z"}
```
I just run a test by clicking the code lens link "Run Test", then the message "Failed to run tests" appears in the status bar. When I click it, the side panel tells me the test was skipped (it's the only test I have in the project currently).
![java_tests](https://user-images.githubusercontent.com/1888641/41764960-eac4e74c-7602-11e8-8364-345175a3c276.png)

The test is running fine when I right-click the project in the "Maven Projects" panel and then click the "test" menu item.

I'm using these versions:
- Visual Studio Code 1.24.1
- Java Extension Pack 0.3.0
- JUnit 4.12
- jdk1.8.0_171

**Comment by ansyral** [comment] 2018-07-04 10:48
@BrightSoul sorry for the late. It seems to be a different issue(java.lang.NoClassDefFoundError: org/junit/runner/JUnitCore). Could you help open another issue to track it? Thanks.

**Comment by ansyral** [comment] 2018-07-12 02:48
@BrightSoul we've just released a new version, which has the fix and exposes a command `Java: Refresh Classpath`, could you help verify whether you could still meet above error and if so would invoking the command resolve it? Thanks. And if you still meet the error, opening a separate issue with details would be appreciated.

**Comment by BrightSoul** [comment] 2018-07-13 07:45
@ansyral, thank you so much! It's working fine now :) Test are run correctly.
![tests](https://user-images.githubusercontent.com/1888641/42678978-d47f7676-8680-11e8-970e-1677d193703e.png)
The issue is resolved for me.

**Comment by koonchen** [comment] 2018-09-30 02:54
It works by using `Java: Refresh Classpath` 😯!

**Comment by jdneo** [comment] 2018-09-30 04:16
Closing the issue since looks like it has been solved.

**Closed by jdneo** 2018-09-30 04:16 UTC
