### ISSUE TITLE
Load test cases only when necessary (Delay load)

### ISSUE THREAD

**Issue by akaroml** [Microsoft/vscode-java-test#259] opened 2018-07-26 13:50 UTC
Loading test cases occupies considerable amount of time of project load. Check the performance test result below:

<img width="774" alt="screen shot 2018-07-26 at 9 42 08 pm" src="https://user-images.githubusercontent.com/16755094/43266113-16b326ae-911d-11e8-8cef-303b9848aaa0.png">

There is a significant gap between loading a project with or without the test runner.

Please delay load test cases to the moment when users show the intentions to use them. Here are some possible scenarios (but not limited):
- When users toggle the visibility of Test Explorer
- When users open a Java file with tests and code lens needs to be visible
- When users run test cases by triggering some command

As a result, we reduce the chance of loading all test cases along with project load to improve experience.

**Comment by ansyral** [comment] 2018-08-27 07:05
Currently we fetch all the tests and store them into the storage when the extension is activated. So to delay fetching tests until the user accesses Test Explorer , I plan to do the following changes:
1. Not load all the tests from the beginning(`TestResourceManager.refresh()`).
2. For Test Explorer, fetch the children and update test storage when `getChildren()` is called by vscode.
3. Add incremental refresh function for test explorer.
if a class is updated(add/remove/update test methods), reload its parent, this class and its children.

**Comment by ansyral** [comment] 2018-08-28 05:52
Found one bug test: storage isn't updated when a test file is removed. Opened a pr #277

**Comment by akaroml** [comment] 2018-08-29 13:17
Appreciate the effort of breaking down the problem. The logic of resolving test cases level by level looks fine to me. My thought is regarding

> I don't want the packages that doesn't contain tests to show in this tree. If we resolve layer by layer, then when resolving the package layer, we call language server to get all the packages defined in this workspace folder. We have no idea whether this package contains test unless we fetch its children.

For this part, I think it's fine to show packages at the top level when they contain no test cases. Hiding the empty ones cause extra computation that I don't think worthy. At the same time, showing all the packages is providing a view that is symmetric to the package truth. So my suggestion would be keeping all the packages at the top level, load their children only when user expand them.

**Comment by jdneo** [comment] 2018-09-11 01:28
### Update:

Current behavior of the explorer: 
![lazyload](https://user-images.githubusercontent.com/6193897/45273330-cc6c6880-b4e4-11e8-840e-bd2c7828129a.gif)

Some todo tasks:
- Clean up the code which is used to load all the tests at once
- Run regression tests
- Fix regression bugs

**Comment by jdneo** [comment] 2018-11-09 03:13
Closing since we have changed to lazy-load in 0.11.0

**Closed by jdneo** 2018-11-09 03:13 UTC
