### ISSUE TITLE
Tests are not found anymore since 0.34.1

### ISSUE THREAD

**Issue by Sandared** [microsoft/vscode-java-test#1381] opened 2022-03-02 10:34 UTC
When using version 0.34.1 (I did so on Gitpod) none of my tests are recognized anymore.
No play button is shown and  also in the Testing View no tests are shown. Everything works fine with 0.34.0

**Comment by jdneo** [comment] 2022-03-02 11:31
Will it help if you re-load the window? Is it occurring for all Java projects?

**Comment by Sandared** [comment] 2022-03-02 12:54
Reloading does not help. I also don't get any error message. It just doesn't show the tests anymore. 
I didn't check it with other Java projects yet, as I don't have that many with tests ^^

**Comment by jdneo** [comment] 2022-03-02 12:56
Thank for the information. Is it possible to share a sample project for this issue?

**Comment by jdneo** [comment] 2022-03-03 02:25
Hi @Sandared,

I tried to make some changes, not sure if I found the root cause or not. Would you mind to try installing this bit and let me know if the problem get solved?

[vscode-java-test-0.34.1.vsix.zip](https://github.com/microsoft/vscode-java-test/files/8174412/vscode-java-test-0.34.1.vsix.zip)

**Comment by liechtir** [comment] 2022-03-03 07:51
Hi @jdneo, I confirm the same issue with the vanilla 0.34.1. When downgrading to 0.34.0 all is back to normal.
Your enhanced version of 0.34.1 also fixes the issue, my tests are back and I can run them.
Thank you, looking forward to get the 0.34.2 then ;-)

**Comment by jdneo** [comment] 2022-03-03 07:55
@liechtir Thank you for the information. I'll wait a little bit more to see if the patch fix @Sandared's problem as well. If yes I'll release a hot fix for this.

Sorry for introducing the issue.

**Comment by Sandared** [comment] 2022-03-03 08:01
Hi @jdneo  ,
awesome work 👍  everything works again!
Thanks for the quick response!

**Closed** 2022-03-04 02:27 UTC
Labels: bug

**Comment by jdneo** [comment] 2022-03-04 03:07
Hi all,

0.34.2 is now planned to release in early next week. In 0.34.2 we also [adopted one new API from VS Code](https://github.com/microsoft/vscode-java-test/issues/1348), so please remember to update your VS Code to 1.65.0.
