### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by oscarAmarello** [microsoft/vscode-java-test#832] opened 2019-10-11 19:02 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-java-test`
- Extension Version: `0.20.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.39.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Eru\
[vscjava.vscode-java-test-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-java-test/files/3719264/vscjava.vscode-java-test-unresponsive.cpuprofile.txt)
vscjava.vscode-java-test-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by jdneo** [comment] 2019-10-12 05:16
Hey @oscarAmarello,

Could you please attach the profile txt as the instrument says in the issue?

**Comment by oscarAmarello** [comment] 2019-10-14 14:38
Hi @jdneo 

Here is the file

[vscjava.vscode-java-test-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-java-test/files/3724886/vscjava.vscode-java-test-unresponsive.cpuprofile.txt)

**Comment by jdneo** [comment] 2019-10-16 02:23
Thank you @oscarAmarello

**Comment by bernardmo** [comment] 2020-01-03 20:19
I have a similar issue. CPU load gets very high on some test classes and auto complete sometimes takes more than 20s to display (running on i7 8th gen). After some debugging I've managed to pinpoint the issue to `code lens`. Having them disabled didn't cause any problems (or better to say it was tolerable). 

Issue is easly reproducable by creating classes which have a lot of methods with any kind of annotation (I've tested with `@SuppressWarnings`) or propeties with lombok annotations (I've tested with `@Getter` and it turns out that lombok internal implementation creates method with `@SuppressWarnings` annotation). After that typing code within that class will become slower and slower (first few iterations don't hit CPU too much but as you continue typing it gets worse).

Is there a way to prevent code lens to spawn to often (for example to run it only on save)? That would probably save CPU cycles.

**Comment by lijian12345** [comment] 2020-01-17 15:13
[vscjava.vscode-java-test-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-java-test/files/4077409/vscjava.vscode-java-test-unresponsive.cpuprofile.txt)
Same issue.

**Comment by enihcam** [comment] 2020-03-16 01:39
same issue here

**Comment by coryroloff** [comment] 2020-05-05 19:39
I'm having the same issue.

**Comment by Jojoooo1** [comment] 2020-07-21 21:23
I'm having the same issue.

**Comment by andrewglowacki** [comment] 2020-08-11 19:05
I've been having the same issue. It only really happens when using Intellisense and is within the language server (as some have mentioned here: https://github.com/redhat-developer/vscode-java/issues/1064)

Using a [tool](https://github.com/andrewglowacki/jtop) to sample a running JVM using jstack, the hot spot appears to be something to do with looking for Test annotations (maybe) (I assume to display the debug code lens). See this screen shot (not the stack goes even further, but is too big to include in the screen shot)

![slow-stack](https://user-images.githubusercontent.com/5504606/89938062-f6a09680-dbe3-11ea-932d-5b89341640a2.png)
:

**Comment by jdneo** [comment] 2020-08-12 01:54
@andrewglowacki We did a [perf improvement](https://github.com/microsoft/vscode-java-test/pull/1042) recently. It would be great and helpful if you would like to have a try again after the next release. (possibly in next week)

**Comment by andrewglowacki** [comment] 2020-08-12 01:57
@jdneo sounds good, I'll give it a shot when it's available.

**Comment by andrewglowacki** [comment] 2020-08-24 16:29
> @jdneo sounds good, I'll give it a shot when it's available.

Performance is MUCH better with this new version.

CPU usage measured by top (with the eye-ball method) appears much better. I was seeing 2-3 cores at 100% before and even trying to tax it now, seems to be less than 1 core.

Subjectively, Intellisense resolution is also light years faster (< 1 second) in places where it was taking 10+ seconds at times.

Thanks again for the improvements.

**Comment by jdneo** [comment] 2020-08-25 01:38
@andrewglowacki Good to know we have progress here. And we are looking for other methods (adaptive debounce, lazy-load, etc...) to keep boosting the perf. 😃

**Comment by jdneo** [comment] 2020-09-07 07:53
@all

`0.24.2` has been released which contains some perf improvement when resolving the completion list in a Java test file. Plesae give it a try.

Thanks.

**Comment by jdneo** [comment] 2020-10-14 03:10
Close since the problem looks resolved so far. But please let us know if you still observe any performance issue.

**Closed by jdneo** 2020-10-14 03:10 UTC
