### ISSUE TITLE
Test resource resolution failed with Gradle project

### ISSUE THREAD

**Issue by pierrickrouxel** [microsoft/vscode-java-test#927] opened 2020-01-16 10:59 UTC
I see in your test plan:

> For a Spring Boot project, if both src/main/resource and src/test/resource contain application.properties file, the test runner should pick the one in src/test/resource

I have a Spring Boot multi-modules project built with Gradle.

I try to override the src/main/resources/application.properties of main module with src/test/resources/application.properties inside a submodule. vscode-java-test doesn't find this resource.

If put a src/main/resources/application.properties in the submodule, it overrides the main application.properties correctly.

Can you help me ?

**Comment by jdneo** [comment] 2020-01-17 02:03
Can you provide the launch configuration that the Test Runner resolved when executing the tests?

You can set `java.test.log.level` to `verbose`. Then you will see it in the output channel at the beginning of each test execution.

Thanks.

**Comment by pierrickrouxel** [comment] 2020-01-22 13:21
Setting java.test.log.level to verbose seems to has no effect.

The problem appears with a single module project. I provided you a simple example:

https://github.com/pierrickrouxel/java-test-runner-example

This is a simple Spring boot application. There is two application.properties, one in main sourceSet and the other in test. 
The class DemoApplicationTests should read one value in each file.

Only main test passes.

**Comment by jdneo** [comment] 2020-01-23 02:37
I got the same error if directly trigger the test from command line `./gradlew test`

```
com.example.demo.DemoApplicationTests > testTestValue() FAILED
    java.lang.AssertionError: 
    Expecting actual not to be null
        at com.example.demo.DemoApplicationTests.testTestValue(DemoApplicationTests.java:27)

Gradle Test Executor 5 finished executing tests.

> Task :test FAILED
```

**Comment by pierrickrouxel** [comment] 2020-01-23 08:42
Sorry for the lost time. I did a mistake in my test case. I fixed it.
Now the test passes with Gradle but fails with vscode.

**Comment by jdneo** [comment] 2020-01-30 03:24
It's all passed on my laptop using the latest code.

![image](https://user-images.githubusercontent.com/6193897/73417431-03018800-4353-11ea-924f-38128796cee4.png)

**Comment by pierrickrouxel** [comment] 2020-01-30 08:18
It's doesn't work for me. 

Système: OSX
JDK: "1.8.0_221"
Version: 1.41.1

![Capture d’écran 2020-01-30 à 09 14 43](https://user-images.githubusercontent.com/435273/73431620-20c5f180-4341-11ea-8913-4d7859469f89.png)

**Comment by jdneo** [comment] 2020-01-30 08:30
What's the error message?

**Comment by pierrickrouxel** [comment] 2020-01-30 14:44
```
Message:
N/A
Stack trace:
java.lang.AssertionError: 
Expecting actual not to be null
	at com.example.demo.DemoApplicationTests.testTestValue(DemoApplicationTests.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:675)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:125)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:132)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:124)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:74)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:104)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:62)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:43)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:35)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:202)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:198)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:69)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:137)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```

**Comment by jdneo** [comment] 2020-01-31 05:15
@pierrickrouxel  Maybe the last try:
1. Run the command: `Java: Clean the Java language server workspace` > Select `restart and delete`
2. After the VS Code is reloaded, run `Java: Force Java compilation` > Select `Full`

**Comment by pierrickrouxel** [comment] 2020-01-31 08:23
It works. I will check in my other projects. I encountered this case many times.

**Comment by jdneo** [comment] 2020-01-31 08:36
@pierrickrouxel 

You can set `"java.configuration.updateBuildConfiguration": "automatic"` into your workspace settings to avoid manually building your projects.

I'm closing the issue since the problem is resolved.

**Closed by jdneo** 2020-01-31 08:36 UTC
