### ISSUE TITLE
Can not launch junit tests anymore

### ISSUE THREAD

**Issue by SHemmis** [microsoft/vscode-java-test#1494] opened 2022-10-05 12:07 UTC
### Environment

System : Linux Mint 19.2 (Tina)
JDK: openjdk version "17.0.4" 2022-07-19 (build 17.0.4+8-Ubuntu-118.04)
VSCode: v1.71.2
redhat.java: v1.11.0
vscjava.vscode-java-test: v0.37.1
vscjava.vscode-java-debug: v0.44.0

### Symptom

This is basically the same issue (at least the same symptoms) as in #1481 
This started happening from 1 day to the next on all my projects and workspaces (last week tuesday everything seemed ok, wednesday morning none of my unit tests would run).
If I try to run a junit test the following popup with message "Run Tests: Resolving launch configuration" appears and never disappears 

![image](https://user-images.githubusercontent.com/115082594/194055622-e1ec6b07-61c8-4f12-990c-d0a1e5d51a08.png)

I attached a project where this happens, but I assume this is not related to the project itself since it happens on all projects.
I can't find a good reason or trigger why this happened overnight.

The test runner for java is at 0.37.1, but even with the pre-release version it doesn't work. 

[sudoku.zip](https://github.com/microsoft/vscode-java-test/files/9715394/sudoku.zip)

**Comment by SHemmis** [comment] 2022-10-06 08:12
The biggest issue is that I don't have a warning or error or something message that could give me a hint on where search for the problem...

**Comment by SHemmis** [comment] 2022-10-06 10:10
I tried reverting vscjava.vscode-java-debug to v0.43.0 (was updated mid last week, so a potential cause), but this didn't help.

**Comment by jdneo** [comment] 2022-10-08 01:48
Have you tried triggering the command `Java: Clean Java language server workspace`?

And meanwhile, instead of running tests, does launching main method work?

**Comment by SHemmis** [comment] 2022-10-10 06:26
@jdneo ,

Thank you for your suggestions.

The "Java: Clean Java language server workspace" doesn't help.
And indeed. launching a main method doesn't work either. 
I get the small debug popup window (with pause, step over, step in, step out, restart and stop button), 
and a blue loader thingy underneath the RUN AND DEBUG menu (left column)

![image](https://user-images.githubusercontent.com/115082594/194808404-554d238f-6848-4a45-8065-a3b6891e2f6b.png)

I started looking at logs and found that in the "Language support for java (Syntax Server)" output,

There is this error message.
```
WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.foreign
[Error - 08:17:25] Connection to server got closed. Server will not be restarted.
```
I restarted VSCode and saw that this message is there at startup; so not (direcly) linked to running a test; but maybe it's an indicator that could help figuring out what's going wrong?

**Comment by jdneo** [comment] 2022-10-10 06:45
`[Error - 08:17:25] Connection to server got closed. Server will not be restarted.`

This log indicates that the backend language server is not working due to some reason.

Is there any error logs? See: https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging

**Comment by SHemmis** [comment] 2022-10-10 07:12
In attachment you can find the logging from 
Language Server for Java (LSfj.txt), Language Server for Java (Syntax server) (LSfJSyntax.txt), and the additional logging that happens when running a junit test.  (LSfj-runJunitTest.txt)

Starting the main method didn't add any logs in these 2. I cannot see any obvious errors.

[LSfj.txt](https://github.com/microsoft/vscode-java-test/files/9743860/LSfj.txt)
[LSfj-runJunitTest.txt](https://github.com/microsoft/vscode-java-test/files/9743861/LSfj-runJunitTest.txt)
[LSfJSyntax.txt](https://github.com/microsoft/vscode-java-test/files/9743862/LSfJSyntax.txt)

**Comment by SHemmis** [comment] 2022-10-10 07:39
The developer tools console does show some errors at startup:
[vscode-app-1665387311865.log](https://github.com/microsoft/vscode-java-test/files/9743999/vscode-app-1665387311865.log)

The Java Language Server log file doesn't contain errors:
[JavaLanguageServerLog.txt](https://github.com/microsoft/vscode-java-test/files/9744018/JavaLanguageServerLog.txt)

**Comment by jdneo** [comment] 2022-10-10 08:23
Looks like related with this issue : https://github.com/redhat-developer/vscode-java/issues/2577#issuecomment-1208922149

**Comment by SHemmis** [comment] 2022-10-10 08:45
Indeed, it does look similar.

I tried adding (all 3) suggested changes from #2577 to the settings.json:
```
    "java.debug.settings.vmArgs": "-Xlog:jni+resolve=off",
    "spring-boot.ls.java.vmargs": ["-Xlog:jni+resolve=off"],    
    "java.jdt.ls.vmargs": "-Xlog:jni+resolve=off",
```
But it doesn't help. The Developer Tools console keeps showing this "Header must provide a Content-Length property" error message, and junit tests or java main still doesn't run.

**Comment by SHemmis** [comment] 2022-10-10 09:01
Eureka!
I've tried the suggestion from https://github.com/spring-projects/sts4/issues/811 
(using -Xlog:disable)
```
    "java.jdt.ls.vmargs": "-Xlog:disable",
```
And this works. 
I can run junit tests and java applications again.
Not sure how to proceed from here. 
For me the issue is solved by having a workaround, 
but it has been a pain, and I'm afraid that when I'll have to do a reinstall; or move to a new machine, I'll have the same issue again.

**Comment by SHemmis** [comment] 2022-10-10 09:19
Disabling the Spring Boot Tools plugin also helps

**Comment by jdneo** [comment] 2022-10-10 09:29
Thanks for sharing the findings. I'll close this issue since it looks like the problem is not caused by this extension.

BTW, maybe file an issue at Spring Boot Tools plugin's repo?

**Closed by jdneo** 2022-10-10 09:29 UTC
Labels: need more info

**Comment by SHemmis** [comment] 2022-10-10 09:53
@Jdneo,

thanks for your help. 
The issue https://github.com/spring-projects/sts4/issues/811 seems to cover this issue.
