### ISSUE TITLE
Support for TestNG

### ISSUE THREAD

**Issue by oakad** [Microsoft/vscode-java-test#53] opened 2017-12-13 00:39 UTC
TestNG may be a bit of a niche, but it's a good and cozy niche to be in. Are there any plans to support it as well?

**Comment by ansyral** [comment] 2017-12-13 08:21
@oakad TestNG is in our plan :smile:

**Comment by RogueHat** [comment] 2018-04-04 20:32
@ansyral  Got an ETA for that?

**Comment by chrisaige** [comment] 2018-05-17 13:52
When will we get this?

**Comment by tylerteem** [comment] 2018-08-22 22:11
Will this happen?

**Comment by yahudev** [comment] 2018-10-11 06:51
When will this happen?

**Comment by jdneo** [comment] 2018-11-09 02:19
Hi @all,

We have added the TestNG support in the newest code base. It should be released recently. So I'm closing this issue for now.

**Closed by jdneo** 2018-11-09 02:19 UTC
Labels: feature

**Comment by ANK-13** [comment] 2019-02-20 11:09
Testng is not able to throwing class not found Error. Can Anyone help? In eclipse, it works fine

**Comment by jdneo** [comment] 2019-02-20 11:43
@ANK-13 Sorry for this issue. The root cause is that the error handling mechanism needs to be improved.  We have an issue tracking that: https://github.com/Microsoft/vscode-java-test/issues/355
