### ISSUE TITLE
Refactor The Rendering of Output In The Test Results Panel

### ISSUE THREAD

**Issue by lingocoder** [microsoft/vscode-java-test#1618] opened 2023-09-28 19:20 UTC
### The Problem
Rendering of the text in the Test Results panel is practically unreadable&hellip;

![issue 1618 test results -10 a](https://github.com/microsoft/vscode-java-test/assets/49788472/0358e95f-eb88-43fe-b096-0ebf103bbea7)

### Steps to reproduce
1. Download and decompress [_this reproducer_](https://bit.ly/issue1618Reproducer)
2. Open the project in vscode
3. Run the sole test in the project
4. Observe the Test Results panel

### Version Info

Visual Studio Code - Insiders
Version: 1.83.0-insider (user setup)
Commit: 623feb6ddd36&hellip;
Date: 2023-09-28T11:51:23.482Z (7 hrs ago)
Electron: 25.8.2
&hellip;
OS: Windows_NT x64 10.0.19045

**Comment by jdneo** [comment] 2023-09-29 01:50
I can also reproduce it. But when running the second time and so on, it becomes normal.

I guess it's an upstream regression. I need to find a way to reproduce it via the official extension sample, and file an issue at upstream.

**Comment by lingocoder** [comment] 2023-09-29 18:25
Thanks for looking into this, @jdneo

> &hellip;But when running the second time and so on, it becomes normal.&hellip;

I haven't been as lucky as you have on retries. In my case, it happens without fail every time I run any test.

Test failures are the worst because the more text output to the view (_exception stack traces, for example_)  , the less readable stuff is.

**Comment by jdneo** [comment] 2023-09-30 02:34
My feeling is that it's an upstream bug, the VS Code testing API does not expose anything that can control the font/style.

Unfortunately, I tried the [extension sample](https://github.com/microsoft/vscode-extension-samples/tree/main/test-provider-sample) hoping to reproduce it and file an issue to VS Code but failed.

I guess it might be related with the markdown format. This extension uses markdown content to set the test status.

I'm in vacation right now, may not have time to dig deeper into it. If anyone can help investigate the issue, that would be so helpful!

**Comment by jdneo** [comment] 2023-10-25 02:59
Filed on issue upstream: https://github.com/microsoft/vscode/issues/196521.

**Comment by WildPenquin** [comment] 2023-11-30 10:36
Hi, any workaround for this problem?

All my tests are useless when run via the plugin. I can not get the output window to normal formatting (sorry for the noise, I know these are not supposed to be support channels).

**Comment by WildPenquin** [comment] 2023-11-30 12:22
@jdneo,

Thanks, but that workaround does not have any effect here. All test result formats are still wrong / nearly unreadable.

**Comment by jdneo** [comment] 2024-03-20 08:32
I've tried couple of times and I cannot reproduce this issue with:

Version: 1.88.0-insider
Commit: f7c827a5e0ddbba66425ea54e33430bce8f53c84
Date: 2024-03-20T05:49:22.227Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.88.0-insider Chrome/120.0.6099.291 Electron/28.2.6 Safari/537.36

Should be fixed upstream. Please leave comment if it's still observable.

**Closed by jdneo** 2024-03-20 08:32 UTC
Labels: upstream
