### ISSUE TITLE
CodeLens error: "actual command NOT FOUND"

### ISSUE THREAD

**Issue by bonaluo** [microsoft/vscode-java-test#869] opened 2019-11-01 14:33 UTC
Issue Type: <b>Bug</b>

Can not run test

![image](https://user-images.githubusercontent.com/27731323/68031899-89c4ab80-fcf7-11e9-9c63-24aa1100d0d3.png)

Extension version: 0.21.0
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (0.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jdneo** [comment] 2019-11-02 06:38
Hi @bonaluo,

Can you provide more information about this issue? A sample project would be helpful.

**Comment by jdneo** [comment] 2019-11-18 02:16
@bonaluo Please feel free to let me know if there is anything I can help.

**Comment by bonaluo** [comment] 2019-11-18 05:55
@jdneo I don't know why it happend but it did. The following is a sample that cause the problem.
![image](https://user-images.githubusercontent.com/27731323/69027626-8ecd6e80-0a0a-11ea-9949-52747dcd12ef.png)
![image](https://user-images.githubusercontent.com/27731323/69027644-9b51c700-0a0a-11ea-80d8-609ff5071e55.png)

It worked at first and then it failed, and then immediately before I sent this message, it went back to work.

**Comment by jdneo** [comment] 2019-11-18 06:54
@bonaluo Is this happening in all of your Java project or it's just this one?

**Comment by jdneo** [comment] 2019-11-18 07:08
It would be helpful if you can provide a sample project for reproducing this.

**Comment by bonaluo** [comment] 2019-11-18 07:15
@jdneo I don't think my project is special, and it just happens sometimes. "actual command not found", which may be a problem with vscode.

**Comment by jdneo** [comment] 2019-11-18 07:22
Seems tracking here: https://github.com/microsoft/vscode/issues/84153

**Comment by jdneo** [comment] 2020-01-08 02:41
Closing since it seems that the bug has been fixed from upstream. See: https://github.com/microsoft/vscode/issues/84153

**Closed by jdneo** 2020-01-08 02:41 UTC
Labels: upstream
