### ISSUE TITLE
Failed to run spring boot tests

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-java-test#1546] opened 2023-03-14 00:02 UTC
@nickzhums @martinlippert I've installed the pre-release version of Spring Boot Tools. I can confirm that I had no issues with autocompletion at the time of the usage. However, the test span was rather short, ~10 minutes. But normally it was enough to just change a symbol once to encounter the bug. So, a green light from me.

However, after installing the said extension I also did launch the test suite run with the other extension that is called Test Runner for Java (vscjava.vscode-java-test). And the difference was, that the test suite that used to be green before Spring Boot Tools installation now became partially red. "SpringBootTest"-based tests went red, with the following error:
`javax.management.InstanceAlreadyExistsException`

I've removed the extension, and the suite went green again. I guess, this issue is well described here:
https://github.com/microsoft/vscode-java-test/issues/1420

Thanks

_Originally posted by @nikitades in https://github.com/redhat-developer/vscode-java/issues/1765#issuecomment-1465869177_

**Comment by jdneo** [comment] 2023-03-14 00:04
@nikitades instead of uninstalling the extension. Have you tried to turn off `boot-java.live-information.automatic-connection.on`?

**Comment by nikitades** [comment] 2023-03-14 12:59
@jdneo I can confirm that with
`"boot-java.live-information.automatic-connection.on": false`
Extension "Test runner for Java" starts working properly, and "already exists" error does not appear anymore.

All good.

**Comment by jdneo** [comment] 2023-03-15 01:25
@nikitades Thanks for the update.

---

Hi @BoykoAlex

I remember this issue is fixed with https://github.com/spring-projects/sts4/commit/ec8a5a87ba5b06e8bb4e0fd6ef71405ab1cd0b34. Looks like it appears again recently. Is there anything changed at the spring boot extension side?

**Comment by martinlippert** [comment] 2023-03-15 09:00
@jdneo Can you share the launch config of the tests that you are running?

**Comment by jdneo** [comment] 2023-03-15 09:17
The launch config looks like if I run the tests from the spring petclinic project.
```
{
  "name": "Launch Java Tests - $(symbol-class) ValidatorTests",
  "type": "java",
  "request": "launch",
  "mainClass": "org.eclipse.jdt.internal.junit.runner.RemoteTestRunner",
  "projectName": "spring-petclinic",
  "cwd": "C:\\Users\\xxx\\Documents\\work\\sample-project\\spring-petclinic",
  "classPaths": [
    ...
  ],
  "modulePaths": [],
  "args": [
    "-version",
    "3",
    "-port",
    "57985",
    "-testLoaderClass",
    "org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader",
    "-loaderpluginname",
    "org.eclipse.jdt.junit5.runtime",
    "-testNameFile",
    "C:\\Users\\xxx\\AppData\\Local\\Temp\\xxx.txt",
    "--exclude-tag",
    "aaa"
  ],
  "vmArgs": [
    "-ea"
  ],
  "noDebug": true,
  "__progressId": "889e23e4-92ff-445b-bc0b-7a10892c5342",
  "console": "internalConsole"
}

```

 @nikitades could you share a sample project for this issue?

**Comment by BoykoAlex** [comment] 2023-03-15 15:43
@jdneo It'd be great to fully reproduce this use case. Share the project with the **testFileName** file and contents... Or provide instructions how this `launch.json` has been generated as it seems like i have assemble missing pieces of the config manually (i.e. classpath test class names file etc).
Sounds like you were able to reproduce the issue with **spring-petclinic** project... Please provide instructions on how to reproduce this issue starting from the "vanilla" petclinic project downloaded from spring io.

There is nothing changed around launching and connecting to apps as far as I remember...  I also see that `canConnect(...)` method checks if main class is not one of the test runner classes (i.e. `org.eclipse.jdt.internal.junit.runner.RemoteTestRunner`) [here](https://github.com/spring-projects/sts4/blob/main/vscode-extensions/vscode-spring-boot/lib/debug-config-provider.ts#L134). The config above has exactly the class name that is being watched for thus I'm puzzled why it is an issue...

I have tried launching the tests from the tab (don't think there is `launch.json` generated for this) as well as just running all tests within a test class - all seems to run fine. My attempt to launch the config above ended with unable to connect via port... but I'll keep trying for now until i have better steps to reproduce the issue.

**Comment by jdneo** [comment] 2023-03-16 00:27
@BoykoAlex I'm not able to reproduce it via the spring-petclinic. It's just working perfectly.

The launch config I shared just in case if there is any clue to troubleshoot the problem.

Recently there are several reports about the `boot-java.live-information.automatic-connection.on` will impact the test execution. Besides this issue, another one can be found here: https://github.com/microsoft/vscode-java-test/issues/1530. But unfortunately, none of the users shared a sample project 😢.

**Comment by BoykoAlex** [comment] 2023-03-16 14:42
I see, thanks for the clarification... Seems like I'd need a sample project to reproduce this as well...

**Comment by bradlord** [comment] 2023-05-15 15:09
I'm experiencing the same issue, where tests are failing with a `javax.management.InstanceAlreadyExistsException` when the tests are run through Test Explorer with STS's live information enabled. Here is a repository containing a minimal example:

https://github.com/bradlord/spring-boot-sts-test-failure

The tests in that repository succeed when `boot-java.live-information.automatic-connection.on` is set to false, but they fail when it is true. The key to reproducing the error seems to be defining multiple test classes with different parameters in the `@SpringBootTest` annotation:

```
@SpringBootTest
class DemoApplicationTests {/* ... */}
```

```
@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
class MoreDemoApplicationTests {/* ... */}
```

Thank you.

**Comment by BoykoAlex** [comment] 2023-05-15 16:26
@bradlord I couldn't get the gradle project working in vscode, therefore, I have convrted your project into Maven project:
[sts-test-failure.zip](https://github.com/microsoft/vscode-java-test/files/11479867/sts-test-failure.zip)

Tests run fine... do you mind tweaking that specific Maven project into something that has test failures? It is important to include `.vscode` folder under your project as well as it might be that your creating a launch config that results in the test failures... I launched tests by opening the test source and clicking on the test run icon in the gutters.

**Comment by BoykoAlex** [comment] 2023-05-15 16:30
@bradlord  actually, NVM, got one of the tests to fail if run from the explorer

**Comment by BoykoAlex** [comment] 2023-05-15 17:02
@bradlord fixed with https://github.com/spring-projects/sts4/commit/a9060058d33791569b2e05b4247741c135540a32 Feel free to try the pre-release version of **Spring Boot Tools** a few days later. Thanks very much for reporting this and providing a test project!

**Comment by jdneo** [comment] 2023-05-16 01:35
Thank you for the help @BoykoAlex!

**Closed** 2023-05-16 01:36 UTC
