### ISSUE TITLE
Repeated codelens

### ISSUE THREAD

**Issue by sallyur** [Microsoft/vscode-java-test#156] opened 2018-03-29 09:47 UTC
It is not a regression issue ,it is also repro in  0.4.0
1. Clone junit projects from https://github.com/junit-team/junit5-samples
2. Open the junit5-samples-master project
3. Open firstTest.java file

![image](https://user-images.githubusercontent.com/28860891/38082292-c41a8222-3378-11e8-80e2-7504c11a609f.png)

**Comment by bsaby** [comment] 2018-10-10 08:48
Close this issue  because it cannot be reproduced in version 0.10.0

![image](https://user-images.githubusercontent.com/22470312/46724214-20b56480-ccac-11e8-9ea7-cc7a321864bb.png)

**Closed by bsaby** 2018-10-10 08:48 UTC
Labels: bug
