### ISSUE TITLE
Check Mark White not Green

### ISSUE THREAD

**Issue by spottedmahn** [microsoft/vscode-java-test#925] opened 2020-01-14 18:41 UTC
My ✔ and ❌ are white and not green and red as I see in [the guide](https://code.visualstudio.com/docs/java/java-testing).

![image](https://user-images.githubusercontent.com/14079228/72371741-fe8e6b80-36d2-11ea-9378-1ad7accc2b38.png)

![image](https://user-images.githubusercontent.com/14079228/72371748-00582f00-36d3-11ea-9df4-20a394825934.png)

[the guide](https://code.visualstudio.com/docs/java/java-testing):

![image](https://user-images.githubusercontent.com/14079228/72371767-077f3d00-36d3-11ea-9223-88c738e2f5e8.png)

Java Test Runner: 0.22.0
Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

---

Is it supposed to be that way now?  Is this a bug?  Is this a VS Code issue or Java Test runner issue?  My configuration?

**Comment by spottedmahn** [comment] 2020-01-14 18:43
Nit: the alignment is off too

![image](https://user-images.githubusercontent.com/14079228/72372119-c5a2c680-36d3-11ea-804f-44cffabcde83.png)

**Comment by jdneo** [comment] 2020-01-15 02:08
Hi @spottedmahn, 

The white icons in Code Lens is by design. We made this change in [#845](https://github.com/microsoft/vscode-java-test/issues/845). While the document should be updated. I'll update them recently, thank you!

About the alignment issue, it's actually controlled by VS Code, the extension has nothing to do with it. There is [an issue](https://github.com/microsoft/vscode/issues/87062) tracking for this, which I believe the fix will be released in the next version of VS Code.

Thank you.

**Closed by jdneo** 2020-01-15 02:08 UTC
Labels: question

**Comment by spottedmahn** [comment] 2020-01-15 16:21
>The white icons in Code Lens is by design

Oh 😱.  I guess I'm "old school" and like my colors 😀

Thanks for the quick reply!

And can you undo #845 😂?

**Comment by spottedmahn** [comment] 2020-01-16 15:26
>The reason why we made this change is to make sure all the icons used in extension can align with the VS Code design

That makes sense.  It almost feels like VS 2012 all over again where they stripped away all colors and have been slowly bringing them back!

>So instead of reverting back to the emojis, I suggest to create a request in VS Code repo to allow customizing the color of the codicons. What do you think.

Good call, thanks! 😀
