### ISSUE TITLE
Missing compatibility with Junit 5.4.0+

### ISSUE THREAD

**Issue by DuckNrOne** [microsoft/vscode-java-test#764] opened 2019-08-05 15:57 UTC
Hey,

maybe you can help me. I'm trying to use feature @Order() from the Junit version 5.4.1. But if I want to run the test, nothing happens. In the java, test window stands that 0 tests appear.

Can you help me?

greetz
DuckNr.1

**Comment by jdneo** [comment] 2019-08-06 07:12
Hi @DuckNrOne,

Thank you for reporting this. I just tested on my side, but failed to repro. See:

![demo](https://user-images.githubusercontent.com/6193897/62518541-699e6100-b85c-11e9-9c11-6fe399083397.gif)

So I guess it might not an issue related with `@order` but some other problems there. Is it possible for you to share a sample project to us to repro it? Then I can investigate deeper.

Thanks,

**Comment by DuckNrOne** [comment] 2019-08-06 10:32
Thanks for your quick help.

 I'm kind of confused, but oke :D

I have briefly made the repository public, so that you can have a look. 
[Here ](https://github.com/DuckNrOne/TimeTable/blob/master/src/test/java/czg/antony/timetable/UtilClasses/TestDay.java) is the file.

**Comment by jdneo** [comment] 2019-08-06 12:33
Yes I can repro now. actually the test cases could not run in IntelliJ and Eclipse either:

<img width="1073" alt="Screen Shot 2019-08-06 at 8 29 09 PM" src="https://user-images.githubusercontent.com/6193897/62539898-e0e9ea00-b888-11e9-93c5-c9d284b58077.png">

<img width="744" alt="Screen Shot 2019-08-06 at 8 29 53 PM" src="https://user-images.githubusercontent.com/6193897/62539936-f7904100-b888-11e9-916a-8eb6c9c2e99e.png">

After searching the error message, I got this [answer](https://stackoverflow.com/a/54652059/11620529)

So all you need to do is adding `org.junit.platform:junit-platform-commons:1.4.0` in your `build.gradle`:

```groovy
dependencies {
	testImplementation 'org.junit.jupiter:junit-jupiter-api:5.4.1'
	testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.4.1'
	testCompile 'org.junit.platform:junit-platform-commons:1.4.0'
}
```

After that, the problem is gone:
<img width="343" alt="Screen Shot 2019-08-06 at 8 33 10 PM" src="https://user-images.githubusercontent.com/6193897/62540128-6d94a800-b889-11e9-9f00-b4fe5e898641.png">

**Comment by DuckNrOne** [comment] 2019-08-06 13:26
Thank you very much!

**Comment by jdneo** [comment] 2019-08-07 01:31
@DuckNrOne

I'm closing this issue since it is resolved.

One thing I missed in the above comment is that you can see test runner output in it's output channel.

![image](https://user-images.githubusercontent.com/6193897/62587804-17aa1980-b8f6-11e9-80bb-89b11a0fbede.png)

The log level can be specified with `java.test.log.level`.

**Closed by jdneo** 2019-08-07 01:31 UTC
Labels: question
